### ISSUE TITLE
Online u offline?

### ISSUE THREAD

**Issue by arktrader** [odoo-ecuador/odoo-ecuador#103]
Estimados amigos. Gracias por dar su gran aporte a la comunidad. Solo tengo una pregunta. Éste sistema de facturación es del tipo online u offline según los requerimientos del SRI?

**Comment by ovnicraft** [comment]
@arktrader esta implementado el modo online, estamos trabajando para usar el modo offline

**Comment by arktrader** [comment]
@ovnicraft gracias por tu ayuda. tan solo te pido que cuando desarrolles el modo offline, no sea demasiado traumática la migración o los cambios necesarios para mudarse.. exitos!

**Comment by ovnicraft** [comment]
@arktrader seguro, esperamos poder subirlo hasta finales de mes.
