### ISSUE TITLE
Crear wiki de implementacion y configuracion de modulos contables

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#105]
No contamos actualmente con una documentacion formal respecto a como configurar los modulos publicados de localizacion contable.

**Comment by CarlosJVizcaya** [comment]
Hola yo puedo apoyar con la wiki, si tienen una wiki instalada pueden darme un usuario y asi comenzar la documentacion. 
Tengo una duda con respecto a la facturacion electronica ¿Como puedo indicar contra que ambiente puedo funcionar? si contra el prueba o produccion .

**Comment by ovnicraft** [comment]
@CarlosJVizcaya usamos la wiki de github, aca queremos documentar todo, con tu usuario de github puedes aportar.

https://github.com/odoo-ecuador/odoo-ecuador/wiki
