### ISSUE TITLE
error instalando l10n_ec_invoice_sequence

### ISSUE THREAD

**Issue by arktrader** [odoo-ecuador/odoo-ecuador#106]
Saludos comunidad Odoo Ecuador. Quisieran ayudarme porfa?

Estoy intentando instalar los módulos. Todos funcionan, excepto l10n_ec_invoice_sequence, que me da este error.
`
ParseError: "ValidateError
El(los) campo(s) 'arch' fallaron contra la restricci\xf3n: Invalid view definition
Detalles de error:
El campo 'invoice_number' no existe

Error de contexto:
Vista 'account.invoice.ec.number.form'
[view_id: 922, xml_id: n/a, model: account.invoice, parent_id: 559]" while parsing /opt/odoo/server/custom/addons/odoo-ecuador/l10n_ec_invoice_sequence/views/invoice_view.xml:5, near
![odoo](https://cloud.githubusercontent.com/assets/20035477/16251866/3f3a79e4-37ef-11e6-8d52-c73a1e227151.jpg)

Agradecería mucho su gentileza en decirme que estoy haciendo mal o que es necesario reparar.

Estoy en odoo 8.0. Uso el clon del git a la fecha 21/06/2016. Tengo instalados todos los modulos excepto invoice_sequence, einvoice y withdrawal ya que estos dos ultimos dependen del primero.

Mil gracias. :smile:

**Comment by ovnicraft** [comment]
Puedes crear una base de datos desde cero e instalar solo el modulo `l10n_ec_invoice_sequence` y comentar si se reproduce el error.

**Comment by arktrader** [comment]
@ovnicraft Efectivamente, se repite el error.

Lo he reintentado en una instalación limpia, base de datos limpia. Mismo error en mismo archivo. "El campo 'invoice_number' no existe" generado en l10n_ec_invoice_sequence/views/invoice_view.xml.

Gracias por su valiosa ayuda.

**Comment by ovnicraft** [comment]
No puedo reproducir el error, puedes desde el directorio del repositorio ejecutar el comando: git log --oneline y pegar aca lo que te muestre despues de la ejecucion.

**Comment by arktrader** [comment]
Tengo esto:

ff4aca7 Merge pull request #107 from ovnicraft/8.0
c12c757 FIX module name
c3dce30 Update README.md
acb90df Merge pull request #104 from ovnicraft/8.0
1ce0851 correcion en autorizaciones e implementado numero de factura cliente/proveedor sin romper esquema odoo
108f312 Merge pull request #101 from ovnicraft/8.0
c3492bb migrando reporte de movimiento contable a qweb
de45216 QA
d71ef2c FIX default value
66f9536 DELETE import no existe report
9af7cad Merge branch '8.0' of https://github.com/odoo-ecuador/odoo-ecuador into 8.0
2c8d04c Merge pull request #100 from ovnicraft/8.0
041bdb0 Merge branch '8.0' of https://github.com/ovnicraft/odoo-ecuador into 8.0
0b4aca4 Merge branch '8.0' of https://github.com/odoo-ecuador/odoo-ecuador into 8.0
deebd7f FIX pos dep
fd1e5be FIX
c4e190c README updated
087a75b Merge pull request #99 from ovnicraft/8.0
fb55e86 translation and security models
915f085 Merge pull request #96 from ovnicraft/8.0
76365a6 Merge pull request #91 from ovnicraft/8.0
fe14317 use stdnum lib to validate identifier for Ecuador
3175fe1 TYPO
e17672c README files
f72514f 4 spaces indent XML files
6a21b40 QA
fe8df6e mejora visual en autorizaciones
eb6ff6f  README for all modules
77096b8 QA QA
911cba6 QA QA QA
c5e6fed QA for envoices
7427d52 eliminado asistente invalido
8b57692 QA for advances
a6e22d4 fixes for NC nd QA
6a247d5 Clean code for QA: l10n_ec_reports no se usa, revisar modulos de comunidad para reportes
e45f12c clean reports
9ac6826 Update suds library
d2a637b FIX travis
ef7dc98 Merge pull request #88 from ovnicraft/8.0
cfa8af6 FIX numeracion de retenciones automaticas
560146b Merge pull request #87 from ovnicraft/8.0
4890903 Actualizacion de ATS
d0c7052 Merge pull request #86 from ovnicraft/8.0
306ace6 Actualizaci<C3><B3>n de info
c7a279d Merge pull request #83 from ovnicraft/8.0
198e29e Implementacion de facturacion electronica y correciones en modulo de retenciones y numeracion de documentos
e31d387 FIX tools

Sigo teniendo aún el mismo error... "invoice_number" campo no encontrado...

**Comment by arktrader** [comment]
Reinstalé odoo desde el principio, instalé todas las dependencias del sistema y todos los modulos. Instalé hasta lo que no tenía nada que ver. Ahora funciona, pero no sabría decir qué hice para arreglarlo. Gracias. Cierro el ticket.
