### ISSUE TITLE
Consulta: cómo instalar la firma electrónica en odoo?

### ISSUE THREAD

**Issue by arktrader** [odoo-ecuador/odoo-ecuador#108]
Saludos amigos. Una consulta. He generado ya la firma electrónica en el Banco Central. Adicional, tengo mi odoo 8.0 con todos los módulos de la localización ecuatoriana. Puede ser para ustedes algo sencillo, pero me he perdido aquí. Podrían ayudarme? Gracias y saludos.

**Comment by ovnicraft** [comment]
@arktrader el modulo l10n_ec_einvoice agrega parametros a la compañía que debe ser configurados:
- path a tu archivo **pk12** en el servidor
- password de firma

Es todo lo que debes configurar.

De lograrlo nos ayudaría mucho si puedes apoyarnos con una página en la wiki que describa en breves pasos y de forma muy clara como conseguirlo, así más personas puedar ir directamente allá.

**Comment by ovnicraft** [comment]
Lo cierro hasta pronto feedback
