### ISSUE TITLE
Pull Request - OTE Ecuador

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#123]
Hola, encontre un bug en la OTE con el city_name en la siguiente linea del res_country:

<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <record id="base.ec" model="res.country">
            <field name="currency_id" ref="base.USD"/>
            <field name="address_format" eval="'%(street)s \n%(city_name)s \n%(state_name)s \n%(country_name)s'"/>
        </record>
    </data>

se corrige el city y ya no aparece el error al buscar un cliente en la ventana facturas.

Saludos.

**Comment by ovnicraft** [comment]
puedes detallar en que archivo necesitamos la correcion ?

**Comment by ocurieles** [comment]
No se porque no se ve el codigo que pegue ahi se ve el nombre, pero el archivo es res_country.xml de la carpeta data del modulo l10n_ec_ote

Saludos

**Comment by ovnicraft** [comment]
No se publico un PR
