### ISSUE TITLE
Configurar ambiente de pruebas o produccion

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#124]
Buenos dias donde puedo indicarle al sistema que voy a usar mi facturacion electronica en el ambiente de pruebas o produccion ? no deberia ser un parametro de la organizacion ? donde configuramos el certificado ? .

 Por otra parte donde dice nombre del certificado debo pasar la ruta completa ? o de que manera menciono el nombre del archivo ?

Gracias de antemano

**Comment by ovnicraft** [comment]
@ocurieles si, por ahora esta en el codigo... estamos trabajando esta semana en un update para que sea parametrizable esta opcion.

Respecto a la ruta, si debes pasar toda la ruta del archivo p12

**Comment by ocurieles** [comment]
Gracias @ovnicraft  por la respuesta, de que manera puedo hacer que utilice el ambiente de pruebas ?

**Comment by ocurieles** [comment]
Al usar el boton factura electronica recibo el siguiente error:
File "/home/ocurieles/desarrollo/sources/odoo8/odoo-ecuador/l10n_ec_einvoice/edocument.py", line 90, in get_access_key
    tcomp = utils.tipoDocumento[auth.type_id.code]
KeyError: u'1'

**Comment by ovnicraft** [comment]
Se agrego en la compañia el tipo de ambiente a usar.

**Comment by abdufarag** [comment]
1. En l10n_ec_einvoice/models/edocument.py
Change the code on line 108 from: 
`        - tcomp = utils.tipoDocumento[auth.type_id.code]` 
To:
`       + tcomp = utils.tipoDocumento[auth]`
---------
2. in  l10n_ec_authorisation/models/authorisation.py
Change Line 197 from:
`return a`
To:
`return a.type_id.code`

**Comment by ovnicraft** [comment]
@abdufarag Please can you open a PR to fix this?

**Comment by abdufarag** [comment]
i will do it
thanks very much
