### ISSUE TITLE
Error al imprimir factura de Venta

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#125]
Tengo instalado el modulo de Facturación electronica, al intentar imprimir obtengo el siguiente error:

Webkit render!

need more than 0 values to unpack

Saludos

**Comment by ovnicraft** [comment]
@ocurieles el modulo de facturacion electronica agrega el PDF como adjunto, el pdf actual esta trabajando con MAKO, por esto el error.

**Comment by ovnicraft** [comment]
considero que debemos remover el reporte mako para dejar solo el reporte qweb

**Comment by ovnicraft** [comment]
Este error fue corregido en la version 8.0
