### ISSUE TITLE
Cambios en el Pos

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#126]
Hola muchachos, realice unos cambios en el pos para mostar el tipo de persona 

Adjunto los archivos cambiados.-

Saludos.
[Cambios de l10n_POS_ec.tar.gz](https://github.com/odoo-ecuador/odoo-ecuador/files/397517/Cambios.de.l10n_POS_ec.tar.gz)

**Comment by alcidesrivera** [comment]
@ovnicraft  @ocurieles Según recuerdo se quedo que no se debe tener el tipo de persona en el POS ya que como se conoce es para ventas rápidas, incrementarlo demoraría el ingreso de clientes más bien se debe redefinir la validación de la cédula que es para lo único que se utiliza el tipo de persona.

**Comment by ocurieles** [comment]
Estimado en Ecuador estamos implementando a restaurantes y tiendas al detal y todas necesitan poder facturar a empresas no sólo a personas 

 Saludos

**Comment by ocurieles** [comment]
De todos modos creo que se podría dejar el tipo pasaporte por defecto que no realiza validación y tener disponible para quien necesite utilizarlo

 Saludos

**Comment by ocurieles** [comment]
@alcidesrivera incluso estamos pensando implementar el botón de facturación electrónica para el POS ya que en 2017 será obligatorio

**Comment by alcidesrivera** [comment]
@ocurieles no me refiero a Facturar solo a personas y no a empresas. Me refiero a que el campo esta demás no es necesario, ya que complica el ingreso de información.

**Comment by ocurieles** [comment]
@alcidesrivera entiendo lo de la cedula, creo que para la facturación electronica es obligatorio el tipo de persona, de momento lo usare mientras hacemos lo del validador.

 Saludos.. cierro este ticket entonces

**Comment by ovnicraft** [comment]
Con todo puedes poner un pull request con los cambios para revisarlos y
dejar el log
