### ISSUE TITLE
Migración Modulo POS

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#145]
Cristian estoy migrando el POS a la versión 9, te aviso para no duplicar esfuerzos, apenas termine te notifico en este ticket.

Saludos

**Comment by ovnicraft** [comment]
:+1:

**Comment by ovnicraft** [comment]
@ocurieles tenemos noticias de esto ? seria importante tener una rama de referencia ya que la migración a la versión 10.0 inició.
