### ISSUE TITLE
Problema al instalar l10n_ec_withdrawing

### ISSUE THREAD

**Issue by qsoftcorporation** [odoo-ecuador/odoo-ecuador#147]
Buenas, estoy presento problemas al momento de instalar el addon l10n_ec_withdrawing, puede instalar sin problemas las dependencias, pero al momento de instalar el addon mensionado, me refleja el siguiente error en el log.

> 2016-12-12 16:49:16,051 11732 ERROR odoo8 openerp.http: Exception during JSON request handling.
> Traceback (most recent call last):
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 499, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 516, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 282, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/service/model.py", line 113, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 279, in checked_call
>     return self.endpoint(*a, **kw)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 732, in __call__
>     return self.method(*args, **kw)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 375, in response_wrap
>     response = f(*args, **kw)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/addons/web/controllers/main.py", line 948, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/api.py", line 237, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/addons/base/module/module.py", line 450, in button_immediate_install
>     return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/api.py", line 237, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
>     registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/registry.py", line 324, in new
>     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/loading.py", line 358, in load_modules
>     loaded_modules, update_module)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/loading.py", line 263, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/loading.py", line 163, in load_module_graph
>     init_module_models(cr, package.name, models)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/module.py", line 283, in init_module_models
>     result = obj._auto_init(cr, {'module': module_name})
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/api.py", line 237, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/models.py", line 2687, in _auto_init
>     raise except_orm('Programming Error', 'There is no reference available for %s' % (f._obj,))
> except_orm: ('Programming Error', 'There is no reference available for None')
> 2016-12-12 16:49:16,053 11732 INFO odoo8 werkzeug: 127.0.0.1 - - [12/Dec/2016 16:49:16] "POST /web/dataset/call_button HTTP/1.1" 200 -

![seleccion_045](https://cloud.githubusercontent.com/assets/24528383/21107986/85d00cc0-c061-11e6-98f6-6d81c145acbb.png)
![seleccion_044](https://cloud.githubusercontent.com/assets/24528383/21107985/85cd0458-c061-11e6-95b5-91129cb62478.png)

**Comment by ovnicraft** [comment]
Estas instalando el branch 8.0 ?

**Comment by qsoftcorporation** [comment]
Si estoy utiliando la version 8.0, para poder realizar las pruebas del adoon. Borre toda la instalacion, volvi a realizar todo nuevamente y me sigue dando el mismo error al intentar instalarlo.

**Comment by ovnicraft** [comment]
los modulos de esta localizacion tambien estan en la version 8.0 ?
Ese error he tenido cuando se trata de instalar la 9.0 en la 8.0

**Comment by qsoftcorporation** [comment]
Acabo de hacer todo nuevamente, baje los proyectos con los siguientes
codigos:

git clone https://github.com/odoo/odoo.git --branch 8.0 --single-branch

git clone https://github.com/odoo-ecuador/odoo-ecuador.git --branch 8.0
--single-branch

Inicie el Servidor instale los adoons basicos de contabilidad, compras y
ventas.

Y ahora al quere instalar el adoon de odoo-ecuador l10n_ec_partner, me da
el siguiente error.

Traceback (most recent call last):
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/http.py", line 544,
>> in _handle_exception
>
>     return super(JsonRequest, self)._handle_exception(exception)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/http.py", line 581,
>> in dispatch
>
>     result = self._call_function(**self.params)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/http.py", line 317,
>> in _call_function
>
>     return checked_call(self.db, *args, **kwargs)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/service/model.py",
>> line 118, in wrapper
>
>     return f(dbname, *args, **kwargs)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/http.py", line 314,
>> in checked_call
>
>     return self.endpoint(*a, **kw)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/http.py", line 810,
>> in __call__
>
>     return self.method(*args, **kw)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/http.py", line 410,
>> in response_wrap
>
>     response = f(*args, **kw)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/addons/web/controllers/main.py",
>> line 948, in call_button
>
>     action = self._call_kw(model, method, args, {})
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/addons/web/controllers/main.py",
>> line 936, in _call_kw
>
>     return getattr(request.registry.get(model), method)(request.cr,
>> request.uid, *args, **kwargs)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/api.py", line 268,
>> in wrapper
>
>     return old_api(self, *args, **kwargs)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/addons/base/module/module.py",
>> line 447, in button_immediate_install
>
>     return self._button_immediate_function(cr, uid, ids,
>> self.button_install, context=context)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/api.py", line 268,
>> in wrapper
>
>     return old_api(self, *args, **kwargs)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/addons/base/module/module.py",
>> line 495, in _button_immediate_function
>
>     registry = openerp.modules.registry.RegistryManager.new(cr.dbname,
>> update_module=True)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/modules/registry.py", line
>> 370, in new
>
>     openerp.modules.load_modules(registry._db, force_demo, status,
>> update_module)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/modules/loading.py", line
>> 355, in load_modules
>
>     loaded_modules, update_module)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/modules/loading.py", line
>> 255, in load_marked_modules
>
>     loaded, processed = load_module_graph(cr, graph, progressdict,
>> report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/modules/loading.py", line
>> 143, in load_module_graph
>
>     load_openerp_module(package.name)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/modules/module.py",
>> line 315, in load_openerp_module
>
>     __import__('openerp.addons.' + module_name)
>
>   File "/home/qsoft/Desarrollo/Odoo/odoo8_test/openerp/modules/module.py",
>> line 80, in load_module
>
>     mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/odoo-ecuador/l10n_ec_partner/__init__.py",
>> line 3, in <module>
>
>     from . import partner
>
>   File
>> "/home/qsoft/Desarrollo/Odoo/odoo8_test/odoo-ecuador/l10n_ec_partner/partner.py",
>> line 5, in <module>
>
>     from stdnum import ec
>
> ImportError: cannot import name ec
>
>

Estoy clonando los modulos de manera correcta?

**Comment by ovnicraft** [comment]
Es una dependencia externa para validar identificadores, debes instalar `python-stdnum` y resuelte el error.

**Comment by qsoftcorporation** [comment]
Ya logre instalar los siguientes addon de odoo-ecuador sin problemas:

> l10n_ec_authorisation
> l10n_ec_einvoice
> l10n_ec_partner
> l10n_ec_ote
> l10n_ec_withdrawing
> l10n_ec_invoice_sequence
> l10n_ec_pos

El problema que estaba presentando era que alguas versiones de modulos de python no estaban actualizados, ejemplo el `python-stdnum`.

Luego de resolver esto y al proceder a instalar los addons, observe que tienes un error en la definicion del archivo __openerp__.py de l10n_ec_einvoice ya que estas declarando una vista en la linea 13 como

`'views/report_einvoice.xml',`

Esta vista no existe la que existe en el directorio es la 

`report_einvoice.mako`

Voy a ir probando los addons y cualquier problema informo.

Gracias por la ayuda.

**Comment by ovnicraft** [comment]
Si puedes crear un PR para fix el error, gracias.
