### ISSUE TITLE
Error al Instalar adoon l10n_ec_advances

### ISSUE THREAD

**Issue by qsoftcorporation** [odoo-ecuador/odoo-ecuador#148]
Buenas, cuando trato de instalar el addon l10n_ec_advances, me da el siguiente error en el log.

> Odoo
> OpenERP Server Error
> Traceback (most recent call last):
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 499, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 516, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 282, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/service/model.py", line 113, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 279, in checked_call
>     return self.endpoint(*a, **kw)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 732, in __call__
>     return self.method(*args, **kw)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/http.py", line 375, in response_wrap
>     response = f(*args, **kw)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/addons/web/controllers/main.py", line 948, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/api.py", line 237, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/addons/base/module/module.py", line 450, in button_immediate_install
>     return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/api.py", line 237, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
>     registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/registry.py", line 324, in new
>     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/loading.py", line 358, in load_modules
>     loaded_modules, update_module)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/loading.py", line 263, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/loading.py", line 149, in load_module_graph
>     load_openerp_module(package.name)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/module.py", line 312, in load_openerp_module
>     __import__('openerp.addons.' + module_name)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/openerp/modules/module.py", line 77, in load_module
>     mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/custom-addons/odoo-ecuador/l10n_ec_advances/__init__.py", line 24, in <module>
>     import account_advances
>   File "/home/qsoft/Desarrollo/Odoo/odoo8/custom-addons/odoo-ecuador/l10n_ec_advances/account_advances.py", line 29, in <module>
>     import netsvc
> ImportError: No module named netsvc
> 

![seleccion_046](https://cloud.githubusercontent.com/assets/24528383/21108119/0410591e-c062-11e6-80a8-5d4d31920f54.png)

**Comment by ovnicraft** [comment]
El modulo fue marcado como deprecated desde la version 8, el modulo oficial `account_voucher` soluciona esa funcionalidad.
