### ISSUE TITLE
Archivos de datos tributarios

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#15]
al instalar el modulo debe cargar datos de:
- impuestos
- codigos de impuestos
- sustentos de comprobante
- codigos de documentos

**Comment by codeadict** [comment]
De donde puedo obtener estos datos??

**Comment by ovnicraft** [comment]
@codeadict Los tengo aca, https://www.dropbox.com/sh/bqnofi04thvhm99/AABCixc9thT4ChaywyZjzZjVa si nos ayudas con un PR para ponerlos en cada modulo correspondiente.

seria en el l10n_ec_authorisation y en el withdrawing los impuestos.

**Comment by ovnicraft** [comment]
@codeadict en el l10n_ec se pueden crear plantillas con los planes de cuentas que se tiene en ecuador, sera un muy buen aporte.

**Comment by miltonlab** [comment]
Y como terminó esto, alguien lo realizó o está pendiente todavía??

**Comment by ovnicraft** [comment]
En espera de ayuda.

**Comment by palichis** [comment]
abri el link a dropbox, y me da un "No hay nada aqui"

**Comment by ovnicraft** [comment]
@palichis confirmado, lo reviso.
@codeadict Pudiste bajarlos y subirlos con el modulo ?

**Comment by codeadict** [comment]
Ya le subí esa data pero el módulo no calcula retención de IVA en las facturas y muchos errores más @ovnicraft has visto este problema en las retenciones??

**Comment by ovnicraft** [comment]
@codeadict nos ayudas con un PR para que los archivos se carguen con la instalacion ? 

Si puedes reportar los errores con un traceback adjunto los corregimos.

**Comment by ovnicraft** [comment]
Ya estan en el PR https://github.com/odoo-ecuador/odoo-ecuador/pull/37
@codeadict @palichis

**Comment by ovnicraft** [comment]
Resuelto en https://github.com/odoo-ecuador/odoo-ecuador/pull/37/files
