### ISSUE TITLE
Migracion de Modulos a la version 10.0

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#153]
He subido algunos cambios sobre los modulos segun la nueva estructura de la version 10.0 por cuanto pido su aporte para trabajar en esta migracion.
Los modulos instalables considero un mejor funciomiento.
@alcidesrivera @zamberjo

Migrar:

* [x] l10n_ec_chart
* [x] l10n_ec_tax
* [x] l10n_ec_partner
* [x] l10n_ec_authorisation
* [x] l10n_ec_withholding
* [ ] l10n_ec_einvoice
* [ ] l10n_ec_ote
* [x] l10n_ec_pos
* [x] l10n_ec_employee

**Comment by alcidesrivera** [comment]
A mi parecer deberiamos ir subiendo paulatinamente de versiones recien estoy migrando a 8 en mis clientes ahorita mi concentración esta en esa versión

**Comment by ovnicraft** [comment]
Los cambios son bastante fuertes desde la 9 por cuanto trabajar en la versión 10 para nuevas implementaciones es lo correcto, se simplifica mucho las funcionalidades.

**Comment by dmarante** [comment]
Me pueden ayudar con esta error a la hora de utilizar facturación electrónica. ?? 
Como puedo colaborar con la migracion a odoo 10, ya que he realizado muchas de las modificaciones requeridas. y augunos de los reportes que quedan pendiente.
saludos

mar 29, 2017 3:14:23 PM ec.com.virtualsami.xades_firma.GenericXMLSignature <init>
GRAVE: null
java.io.FileNotFoundException:  (No existe el archivo o el directorio)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ec.com.virtualsami.xades_firma.GenericXMLSignature.<init>(GenericXMLSignature.java:60)
	at ec.com.virtualsami.xades_firma.XAdESBESSignature.<init>(XAdESBESSignature.java:24)
	at Program.main(Program.java:41)

Lista de certificados vacía

odoo 10

**Comment by ovnicraft** [comment]
Para tus contribuciones puedes hacer un fork, subir tus cambios y crear un PR.
Para el error, debes ubicar el archivo en el servidor que estes probando y en la configuracion de la empresa, ingresar el path del certificado y el password.

**Comment by yusniermatos** [comment]
Hola ovnicraft, tengo el mismo error que dmarante pero en la versión 8. En la configuración de la empresa puse el pass y el path hacia el .p12. Por lo que le indicas entiendo que es otra cosa lo que va ahí: el certificado.

Tengo el certificado celcer.sri.gob.ec.crt, pero no sé cómo usarlo, dónde copiarlo, cómo exportarlo.

¿Puedes explicar con un poco más de detalles por favor?

Gracias de antemano por tu ayuda.

**Comment by ovnicraft** [comment]
Tu firma electronica es un archivo PKCS12 que te entrga un ente certificador, por ejemplo el banco central del Ecuador, ese certificado lo ubicas en el server y configuras ese path, user y passwd en la compañía.

**Comment by yusniermatos** [comment]
Gracias ovnicraft,

Revisando el código del jar de firmas lo que vi es que estaba tratando de decodificar el nombre del fichero .p12 y la clave, pero luego las usa como si fueran texto plano. Con esto trata de buscar un fichero pero el nombre es una codificación, no el nombre real y es entonces cuando no lo encuentra, así mismo con la clave.

Le cambié esos datos y firmó, pero al enviar al sri retorna un error de estructura de la firma inválida.
El doc firmado también lo devuelve con algunos datos de más, incluida la clave, además de caracteres de retorno de carro.

No sé si es que tengo una versión desactualizada o estoy algo (más) incorrecto.

**Comment by dmarante** [comment]
Buenas estimado, le escribo para ver si le dio solucion al problema que
presento, que tengo el mismo problema, me dice que el archivo p12 no se
encuentra o es vació

**Comment by ovnicraft** [comment]
@alcidesrivera nos ayudas con el code del jar? 💯

**Comment by ocurieles** [comment]
Yo lo hice funcionar la semana pasada, tengo varias correcciones por sugerir, por ejemplo no es obligatorio que sea contribuyente especial para generar facturacion electronica, tambien en la informacion de la compania colocaron un campo string que indica si es contribuyente especial, tuve que escribir true para que pasara el debug, si los grupos de Iva no son ICE o VAT no entra en los impuestos y da error, aun faltan esos detalles pero esta funcionando.

Saludos.

**Comment by dmarante** [comment]
Ya lo complete, la dificulta esta en el path donde se configura el archivo, tiende a confundir los datos solicitados Firma Electrónica hay que poner la dirección del archivo .p12, los xml tiene errores las soluciones las pretendo enviar en estos dias

**Comment by dmarante** [comment]
Una pregunta al grupo, existe alguna manera de configurar odoo 10 para no
compartir los datos de clientes , productos entre diferentes compañias, en
una misma base de datos. ?

**Comment by ovnicraft** [comment]
lo resuelves con reglas de registros, pero es una pregunta fuerte de tema en este issue.
