### ISSUE TITLE
[8.0] Falla Mensajes de Partner Ecuador en POS

### ISSUE THREAD

**Issue by alcidesrivera** [odoo-ecuador/odoo-ecuador#159]
No se muestran correctamente los mensajes de validación de Cédula ó RUC, o Unicidad de Partners en Ecuador.

Por ejemplo si se coloca mal la Cédula ó RUC el mensaje sale correctamente en el log: "ValidationError: ('ValidateError', u'El(los) campo(s) `ced_ruc` fallaron contra la restricci\xf3n: Error en su Cedula/RUC/Pasaporte')". Pero en la interfaz sale "Error: no se pueden guardar los cambios. Su conexión de Internet está probablemente caída".

**Comment by ovnicraft** [comment]
confirmar que sea en la version 8.0 el error.

@alcidesrivera Tenemos identificado como lanzar mensajes de error en la interfaz POS  ?

**Comment by alcidesrivera** [comment]
Actualmente estamos trabajando en la versión 8.0 para que cumpla con todos los estándares de la legislación tributaria ecuatoriana.

Se encuentra definido desde donde se lanza el mensaje que es en el siguiente trozo de código:

https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/widgets.js#L1046

Creiamos que no funcionaba ya que en log era el mensaje: "ODOO Server Error"  y en el código dice "OpenERP Server Error", pero no funciono al realizar ese cambio.

Y si se desea enviar un mensaje desde un validador se lo realiza de la siguiente manera:

self.pos.pos_widget.screen_selector.show_popup('error', {
                        'message': _t("Warning !!!!"),
                        'comment': _t("(" + product.display_name + ") " + self.pos.config.wk_error_msg + "."),
                    });

Estábamos viendo como alternativa volver a validar la cédula o RUC desde el TPV pero nos parece una duplicidad de validación.

**Comment by ovnicraft** [comment]
Puede validarse del lado del cliente, no lo veo mala opcion a la final es una app web el POS, reportanos algun avance.
Revisare en la 10 que es la versión que vengo trabajando.
