### ISSUE TITLE
Error en tipoDocumento einvoice odoo 8

### ISSUE THREAD

**Issue by Gemgaamg** [odoo-ecuador/odoo-ecuador#165]
![sin titulo](https://cloud.githubusercontent.com/assets/10767373/21862964/7c220b96-d809-11e6-91d7-547d9a8f0d53.png)

En el archivo l10n_ec_einvoice/edocument.py en las siguientes lineas
72            'codDoc': utils.tipoDocumento[auth.type_id.code]
98             tcomp = utils.tipoDocumento[auth.type_id.code] 

reemplazar por utils.tipoDocumento[auth.type_id.code.zfill(2)] para que busque correctamente en el diccionario

**Comment by ovnicraft** [comment]
Por que hacer zfill ?

**Comment by Gemgaamg** [comment]
En el diccionario que esta en utils tipoDocumento 
tipoDocumento = {
    '01': '01',
    '04': '04',
    '05': '05',
    '06': '06',
    '07': '07',
    '18': '01',
} 
Estan con ceros en la izquierda, cuando se pide auth.type_id.code regresa sin  ceros, y produce ese error
KeyError: u'1'

**Comment by ovnicraft** [comment]
Creo que puede corregirse desde el archivo de datos, y no daria error.

**Comment by Gemgaamg** [comment]
Tienes razón, entonces ese es el problema, hay que cambiar el archivo account.ats.doc.csv
![image](https://cloud.githubusercontent.com/assets/10767373/21866091/b6ed1fec-d816-11e6-9e98-bcfd2515efe3.png)
 por 
![image](https://cloud.githubusercontent.com/assets/10767373/21866156/f8601ab0-d816-11e6-98ca-ae0984596bd6.png)
para que este bien desde la instalacion

**Comment by ovnicraft** [comment]
Si, nos ayudas con un PR para solucionarlo ?

**Comment by Gemgaamg** [comment]
Ok, listo

**Comment by ovnicraft** [comment]
Resuelto en PR https://github.com/odoo-ecuador/odoo-ecuador/pull/166
