### ISSUE TITLE
[8.0][l10n_ec_ote] Formato de Dirección erróneo

### ISSUE THREAD

**Issue by zamberjo** [odoo-ecuador/odoo-ecuador#180]
En el formato de dirección que se añade en el fichero data: [l10n_ec_ote/data/res_country.xml ](https://github.com/odoo-ecuador/odoo-ecuador/blob/8.0/l10n_ec_ote/data/res_country.xml#L6)se añade la clave **city_name** y Odoo sólo parsea el valor **city** (sin `_name`).

¿Es un error tipográfico? o se ha implementado así para alguna implementación posterior?

En el segundo caso se debería de añadir la key en el método que obtiene estas en el res.partner:
```
# -*- coding: utf-8 -*-

from openerp import api, fields, models


class ResPartner(models.Model):
    @api.model
    def _address_fields(self):
        """ [FIX] Añade `city_name` a la lista de campos de la dirección. """
        return super(ResPartner, self)._address_fields() + ['city_name']
```

**Comment by ovnicraft** [comment]
@zamberjo Desconozco, puedes referenciar como esta en odoo ?

Debemos trabajar como odoo lo implementar para no causar efecto colaterales no esperados.

**Comment by zamberjo** [comment]
@ovnicraft 
Ejemplo de data: https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_country_data.xml#L86
List Keys available: https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_partner.py#L172


----
Entonces se debería modificar el data por **city**

**Comment by zamberjo** [comment]
@ovnicraft
Hago un PR con el fix?

**Comment by ovnicraft** [comment]
@zamberjo si, y ahi lo revisamos
