### ISSUE TITLE
Conflictos entre la etiqueta '8.0' y la rama '8.0'

### ISSUE THREAD

**Issue by crimoniv** [odoo-ecuador/odoo-ecuador#188]
Nos hemos encontrado con algunos conflictos a la hora de trabajar con la rama `8.0` por culpa de existir una etiqueta con el mismo nombre. Ya que existe la etiqueta `v8.0`, ¿seria posible eliminar la etiqueta `8.0`?

Muchas gracias y un saludo.

**Comment by ovnicraft** [comment]
Ok ya la elimino.

**Comment by Jaime2ndQuadrant** [comment]
estoy teniendo este mismo problema, al menos creo que es el mismo. Acabo de clonar odoo-ecuador y luego hice un "git checkout 8.0" y el resultado fue:
"""
odoo@apps:~/addons/8.0/odoo-ecuador$ git checkout "8.0"
Note: checking out '8.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 8567d57... Merge pull request #72 from odoo-ecuador/migrate-partner
"""

pero esta parece ser la etiqueta 8.0, aunque puedo hacer un checkout a la etiqueta v.8.0 me pierdo los últimos cambios en la rama (veo algunos tan recientes como hace 4 meses)

**Comment by ovnicraft** [comment]
Borrado.
