### ISSUE TITLE
error al crear factura desde pedido de ventas v8.0

### ISSUE THREAD

**Issue by Jaime2ndQuadrant** [odoo-ecuador/odoo-ecuador#191]
Estaba probando las funcionalidades en la versión 8, y me encontré con este error al crear una factura desde un pedido de venta.
Quizá hay algo que se me paso en la configuración? aún así el error no es bonito :D
[odoo_crear_factura.txt](https://github.com/odoo-ecuador/odoo-ecuador/files/915643/odoo_crear_factura.txt)

**Comment by ovnicraft** [comment]
El cliente no tiene configurada la cuenta o el producto(s) no tiene configurada una cuenta.

**Comment by Jaime2ndQuadrant** [comment]
Efectivamente, al ponerle la cuenta al cliente el error cambia (lo que es un avance ;)
Hay forma de validar, un hook o algo así, antes de que de el traceback? La idea sería ponerle un mensaje de error mas amigable.
