### ISSUE TITLE
problemas para crear Facturas

### ISSUE THREAD

**Issue by efirvida** [odoo-ecuador/odoo-ecuador#193]
Al crear una factura es necesario ponerle el establecimiento, pero los establecimientos después de ser creados no se listan en el formulario de la factura

**Comment by Manzarena** [comment]
Buen dia,

Estoy tratando de generar la factura electrónica pero en este código hace referencia a un campo 'Autorizaciones', que no existe en la table res_partner:

class ResPartner(models.Model):
    _inherit = 'res.partner'

    authorisation_ids = fields.One2many(
        'account.authorisation',
        'partner_id',
        'Autorizaciones'
        )

Por esto no me permite continuar generando una clave que debe validarse. POr favor su ayuda con este bloque de código.

**Comment by ocurieles** [comment]
Hola en que versión de odoo ? yo tengo la V10 y no tengo ese campo pero genero facturas electronicas sin problemas.

Saludos.

**Comment by Manzarena** [comment]
Tengo la version 10, en el codigo l10n_ec_authorisation\models\authorisation.py se encuentra esa parte y me sale el siguiente error:

ERROR AttributeError: 'bool' object has no attribute 'type_id'

Si tienen codigo actualizado me podria ayudar mucho.

**Comment by ocurieles** [comment]
el codigo que tengo es el ultimo que esta en el repositorio, dejame revisar esa clase y te aviso al llegar a la oficina.

**Comment by Manzarena** [comment]
Muchas gracias. Estaré a la espera.

**Comment by Manzarena** [comment]
Buen día, 

Por favor su ayuda aun tengo el error en el codigo l10n_ec_authorisation\models\authorisation.py , me esta devolviendo FALSE ya que no se cumplen las condiciones del FOR

authorisation_ids = fields.One2many(
        'account.authorisation',
        'partner_id'
        'Autorizaciones'
        )
    
    @api.multi
    def get_authorisation(self, type_document):
        map_type = {
            'out_invoice': '18',
            'in_invoice': '01',
            'out_refund': '04',
            'in_refund': '05',
            'liq_purchase': '03',
            'ret_in_invoice': '07',
        }
        code = map_type[type_document]
        for a in self.authorisation_ids:
            if a.active and a.type_id.code == code:
                return a
        return False


ERROR AttributeError: 'bool' object has no attribute 'type_id'

**Comment by jmurillo77** [comment]
Buenas,

Alguien pudo resolver este problema..?
ERROR AttributeError: 'bool' object has no attribute 'type_id'

**Comment by Manzarena** [comment]
No, lamentablemente no dan solución.

**Comment by edwinking** [comment]
Buenas tardes, al tratar de validar una factura aparece este error: 
Error cuando se validaba restricción

'module' object has no attribute 'CODE_701'

alguna solución?? Gracias.
uso odoo v10 en ubuntu 16,04

**Comment by ocurieles** [comment]
La fecha de la factura no puede ser mayor a 5 Dias

**Comment by picassofb** [comment]
Alguien pudo resolver este error??
ERROR AttributeError: 'bool' object has no attribute 'type_id'

**Comment by jomiceve** [comment]
Buenos días @picassofb, yo resolví el problema haciendo unos cambios en la siguiente línea

@api.multi
def get_authorisation(self, type_document):
    map_type = {
        'out_invoice': '18',
        'in_invoice': '01',
        'out_refund': '04',
        'in_refund': '05',
        'liq_purchase': '03',
        'ret_in_invoice': '07',
    }
    code = map_type[type_document]
    for a in self.authorisation_ids:
        if a.active and a.type_id.code == code:
            return a.type_id.code                           <---------------------- EN EL CÓDIGO FUENTE ESTÁ QUE SOLO RETORNA a.
    return False

**Comment by jomiceve** [comment]
Así mismo @picassofb en el modelo edocument.py, se tiene que cambiar la línea del método que acontinuacion te detallo.

def get_access_key(self, name):
        if name == 'account.invoice':
            auth = self.company_id.partner_id.get_authorisation('out_invoice')
            ld = self.date_invoice.split('-')
            numero = getattr(self, 'invoice_number')
        elif name == 'account.retention':
            auth = self.company_id.partner_id.get_authorisation('ret_in_invoice')  # noqa
            ld = self.date.split('-')
            numero = getattr(self, 'name')
            numero = numero[6:15]
        ld.reverse()
        fecha = ''.join(ld)
        tcomp = utils.tipoDocumento[auth]                            <------------- TIENES QUE DEJARLO SIN EL "type_id.code"
        ruc = self.company_id.partner_id.identifier
        codigo_numero = self.get_code()
        tipo_emision = self.company_id.emission_code
        access_key = (
            [fecha, tcomp, ruc],
            [numero, codigo_numero, tipo_emision]
            )
        return access_key

ESPERO TE SIRVA LA RESPUESTA.....

**Comment by picassofb** [comment]
@jomiceve Gracias por tu respuesta, voy a provar y te confirmo.

**Comment by ovnicraft** [comment]
@jomiceve puedes crear un PR para las correcciones ?
