### ISSUE TITLE
[10.0] Error al instalar el plan de cuentas

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#194]
Buenas tardes, al instalar el plan de cuentas no visualizo las cuentas, he probado de varias formas:

1.- Instalando la contabilidad primero y esto instala el plan de cuentas de Ecuador por defecto, instale el plan de ustedes pero no se ven las cuentas.

2.- Instalando primero el plan de ustedes y luego la contabilidad de igual forma no se ven.

Estoy saltando algún paso ?.

 Saludos.

**Comment by ocurieles** [comment]
He visto que hay una opción para cargar el template pero no se despliega este plan de cuentas
![pantallazo](https://cloud.githubusercontent.com/assets/16121174/26082567/44240502-3996-11e7-8375-9604ff2dec5d.png)

**Comment by ocurieles** [comment]
He probado con las 2 opciones y ninguna hace nada, sigo revisando.. :+1:

**Comment by ovnicraft** [comment]
@ocurieles en que version tienes ese error ?

**Comment by ocurieles** [comment]
Es odoo10 @ovnicraft 

Gracias de Antemano

**Comment by ovnicraft** [comment]
El modulo `l10n_ec_chart` de este repo, carga una plantilla de plan de cuentas, que desde contabilidad/Configuracion/configuracion contable puedes seleccionarla, he revisado y esta funcionando ok

**Comment by ocurieles** [comment]
Entro en contabilidad / Configuración y solo veo esto, no veo la opcion que dices Configuración contable

![image](https://cloud.githubusercontent.com/assets/16121174/26119208/1dbaef2e-3a32-11e7-9925-2b4518554f04.png)

**Comment by ovnicraft** [comment]
Ahi en Plan Contable, ya has configurado el plan de cuentas **Ecuador - Chart of Accounts** que es nuestro plan de cuentas, puedes ya hacer uso de las cuentas en tus registros.

**Comment by ocurieles** [comment]
Cuando voy a plan de cuentas solo veo esto amigo:

![image](https://cloud.githubusercontent.com/assets/16121174/26119357/8e5f5f4e-3a32-11e7-9380-07b170357395.png)

**Comment by ovnicraft** [comment]
Puedes verificar que el modulo de plan de cuentas esta instalado y es la version correcta  ?
He creado una DB desde cero y no puedo reproducir el error.
Te recomiendo hacer una prueba con una DB desde cero, instalado el modulo de este repo, y configurando el plan contable para ver el resultado.

**Comment by ocurieles** [comment]
Es la tercera vez que lo intento, he creado una base desde cero, solo instale el plan de cuentas de ustedes y la contabilidad y nada, mira en SQL lo que tengo

![image](https://cloud.githubusercontent.com/assets/16121174/26119472/ea32004c-3a32-11e7-99fb-0102883b352d.png)

**Comment by ocurieles** [comment]
![image](https://cloud.githubusercontent.com/assets/16121174/26119482/f98224a0-3a32-11e7-8ff9-cc86e9a41737.png)
Esos son los módulos que tengo instalados.

Gracias de nuevo

**Comment by ovnicraft** [comment]
Ok, antes de configurar en una DB nueva como se ve la configuracion?

**Comment by ocurieles** [comment]
Mejor te pregunto, sabes que cuando instalas te pregunta tu Pais, coloco Ecuador, luego al instalar la contabilidad el instala el plan de cuentas de Ecuador que trae odoo por defecto, debo desintalarlo antes de instalar el tuyo ?

**Comment by ovnicraft** [comment]
**No** debes seleccionar el pais.
Te dejo un video de como instalado el plan de cuentas.
https://drive.google.com/file/d/0B0sh968wphTxUG0yWk9ZUmpWS00/view

**Comment by ocurieles** [comment]
Y como hago para instalar en un servidor que ya tiene instalado este plan de cuentas standard de odoo ? ya tengo transacciones ahi :(

**Comment by ocurieles** [comment]
@ovnicraft  hice lo que me pasas en el video pero no es tu plan de cuenta si haces este select
 select * from public.account_account_template where name like '%IVA%'
 te trae varios IVA que estan efectivamente en tu módulo pero si vas a plan de cuentas no aparecen estas cuentas, verifica en tu base y te darás cuenta de que no esta montando el plan correcto

select * from public.account_account where name like '%IVA%'

0 registros

**Comment by ovnicraft** [comment]
@ocurieles tendrias que hacer las correciones del caso en los asientos para poder usar las nuevas cuentas.
