### ISSUE TITLE
Error en Partner

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#195]
Hola, al tratar de crear un usuario o un contacto esta pidiendo que se llene el campo identificador ( cédula o ruc) esa validación no debería estar a nivel de constrain sino de la vista.

![image](https://cloud.githubusercontent.com/assets/16121174/26164873/a7ffb630-3af3-11e7-8908-bd15ebf64c2c.png)

Saludos

**Comment by ovnicraft** [comment]
Error corregido.
