### ISSUE TITLE
Error en instalación: Dependencia externa no resuelta.

### ISSUE THREAD

**Issue by estefanoj** [odoo-ecuador/odoo-ecuador#196]
Saludos cordiales,

He intentado instalar los módulos de localización, pero me sale el siguiente error:

**Imposible instalar el módulo "l10n_ec_partner" porqué hay una dependencia externa no resuelta: No module named stdnum**

Hay un archivo requisitos.txt en el que dice algo de aquello pero no lo he podido descifrar.

Les agradezco de antemano su amable ayuda.

Adjunto imagen del error.

![image](https://cloud.githubusercontent.com/assets/18489787/26280394/f6a89b44-3d96-11e7-907b-024b3074c136.png)

**Comment by estefanoj** [comment]
Al parecer tiene algo que ver con la librería phyton:

**'external_dependencies': {
        'python': ['stdnum']**

Por favor su ayuda como puedo resolver este inconveniente en windows para odoo version 10.

**Comment by estefanoj** [comment]
Solucion:

1.- Descargar la librería stdnum en el siguiente link:

https://pypi.python.org/pypi/python-stdnum/

2.- Pegar la carpeta stdnum que se encuentra dentro del archivo descargado en la siguiente ruta:

C:\Program Files (x86)\Odoo 10.0\server

Espero sea de ayuda.

**Comment by ovnicraft** [comment]
@estefanoj gracias por tu aporte.
