### ISSUE TITLE
Como retener impuestos en proceso de Compras

### ISSUE THREAD

**Issue by estefanoj** [odoo-ecuador/odoo-ecuador#197]
El proceso es el siguiente:
  - Ingreso de factura de Proveedores y Validación
  - Ingreso de retención de compras
  - Pago de factura de proveedores

Mi duda es en que momento se descuenta el valor de la retención al pago porque al momento de hacer la retención si se ata a la factura pero no hace ningún descuento o como podría lograr esto?
![image](https://cloud.githubusercontent.com/assets/18489787/26289412/7a5a338e-3e65-11e7-8baa-3eea8226b2ff.png)

**Comment by ovnicraft** [comment]
Lo que requiees es que en la misma factura apliques los impuestos de tipo de retencion, asi el sistema generara la retencion automaticamente.
Por tanto no requiere un ingreso manual.

Sin  embargo de asi hacerlo, cuando ingresas una retencion y te pide seleccionar la factura. asi se cruzara ese movimiento con la factura, puedes verificar en la factura el listado de pagos.

Por favor indicamos que version esta utilizando.

**Comment by estefanoj** [comment]
Saludos,

Es la versión 10, ya entendí son dos asientos diferentes que realmente llegan a lo mismo.

**Comment by estefanoj** [comment]
Saludos,

Tengo un problema con el asiento de la retención (las cuentas me salen al revés)

Hice la factura y me creó el siguiente asiento:

![image](https://cloud.githubusercontent.com/assets/18489787/26362211/e547d442-3fa2-11e7-9ce3-4b3635f9a18e.png)

Luego la retención me hizo el siguiente asiento:

![image](https://cloud.githubusercontent.com/assets/18489787/26362258/07ed78b2-3fa3-11e7-848d-35c7b98385d5.png)

Pero quiero que el asiento de la retención me salga al revés porque aquí me está sumando el valor de la retención y no restandola.

Agradezco de antemano su valiosa ayuda

**Comment by estefanoj** [comment]
Saludos,

Invertí el asiento realizando cambios en el archivo:

**C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\l10n_ec_withholding\models\withholding.py**

En la parte marcada:

![image](https://cloud.githubusercontent.com/assets/18489787/26421400/91931be2-408b-11e7-9bd9-d9c97c84ce79.png)
