### ISSUE TITLE
error al imprimir Comprobante de Retención

### ISSUE THREAD

**Issue by estefanoj** [odoo-ecuador/odoo-ecuador#198]
Saludos cordiales,

Al momento de querer imprimir el comprobante de retención me muestra el siguiente error:

![image](https://cloud.githubusercontent.com/assets/18489787/26434005/afe3b666-40cb-11e7-9179-3d12117ae678.png)

Revisé en los reportes creados y no consta el **l10n_ec_withholding.account_withholding_report**

![image](https://cloud.githubusercontent.com/assets/18489787/26434036/e2b06170-40cb-11e7-9e74-364d6016a136.png)

De antemano agradezco su ayuda.

**Comment by ovnicraft** [comment]
La implementacion del reporte de retencion esta pendiente, cualquier aporte es bienvenido.
