### ISSUE TITLE
Las retenciones de IVA toman como base el monto total de la factura y no el monto del IVA

### ISSUE THREAD

**Issue by codeadict** [odoo-ecuador/odoo-ecuador#20]
Las retenciones de IVA toman como base el monto total de la factura y no el monto del IVA. Ver imagen Ajunta debería tomar como base 120 y se toma 1000 Dolares:

![screenshot from 2014-08-11 16 45 54](https://cloud.githubusercontent.com/assets/168440/3883446/621c74d2-21a1-11e4-9468-87946bc3755c.png)

**Comment by ovnicraft** [comment]
@codeadict  Ok, que porcentaje esta aplicado para el impuesto 721 retencion del 30% ?
Este desarrollo esta pensado para que se aplique sobre la base (con las consideraciones del caso para las declaraciones), el 30% tiene que ser 0.036 y el 70% 0.084

**Comment by ovnicraft** [comment]
@codeadict algun feedback ?

**Comment by ovnicraft** [comment]
No se ha tenido respuesta.
