### ISSUE TITLE
Error al Crear usuario

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#202]
Al intentar crear un usuario de un Cliente da el error de identificador, agregue esto al modelo partner.py del 10n_ec_partner 

identifier = fields.Char(
        'Cedula/ RUC',
        size=13,
        required=True,
        default = '9999999999',
        help='Identificación o Registro Unico de Contribuyentes')

ya que ese campo identifier es obligatorio.

Saludos.

**Comment by ovnicraft** [comment]
En que version tienes este error ?

**Comment by ocurieles** [comment]
Odoo 10 Amigo.

Saludos.

**Comment by ovnicraft** [comment]
@ocurieles en la version mas reciente esta resuelto el issue
