### ISSUE TITLE
Problema en retenciones cero Dias

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#205]
He corregido la clase Withholding ya que si una retencion la recibo el mismo dia no me dejaba ingresarla, adjunto el path.

**Comment by ocurieles** [comment]
[Fix_Zero_Days_on_Withholding.patch.tar.gz](https://github.com/odoo-ecuador/odoo-ecuador/files/1299957/Fix_Zero_Days_on_Withholding.patch.tar.gz)

**Comment by ovnicraft** [comment]
Para seguir un procedimiento normal, por favor crea un PR.
