### ISSUE TITLE
[10.0] Generacion del ATS

### ISSUE THREAD

**Issue by Gemgaamg** [odoo-ecuador/odoo-ecuador#208]
El ats no esta migrado a Odoo 10?
En el modulo withholding han ocultado esa parte

**Comment by ovnicraft** [comment]
@Gemgaamg Se puede revisar en la rama 8.0 el ATS, de pronto nos puedes colaborar con esa migracion :-)

**Comment by Gemgaamg** [comment]
@ovnicraft   Tengo ya listo esa parte pero con varios cambios mínimos en otros módulos, ¿como podría colaborar?

**Comment by ovnicraft** [comment]
@Gemgaamg puedes poner un pull request y validamos los cambios.

**Comment by ovnicraft** [comment]
Pendiente de un PR, hasta tanto cierro el issue.
