### ISSUE TITLE
Migración a la versión 8.0

### ISSUE THREAD

**Issue by miltonlab** [odoo-ecuador/odoo-ecuador#21]
@ovnicraft Tienen planes de pasarlo a la 8.0? Yo he empezando con el modulo l10n_ec, como envio los cambios (si te es que creas el branch para la 8.0)?

**Comment by ovnicraft** [comment]
Esta creada: https://github.com/odoo-ecuador/odoo-ecuador/tree/8.0

**Comment by ovnicraft** [comment]
La mejor manera es que en tu fork hagas tus cambios y los aplicamos aca con un PR. @miltonlab
