### ISSUE TITLE
Creación de Empresa en Odoo 10

### ISSUE THREAD

**Issue by rlguerrero888** [odoo-ecuador/odoo-ecuador#212]
Buenas noches,
Por favor solicito su ayuda despejando la siguientes dudas. 

1. En el formulario para crear compañías solicita:
Servicio de Rentas Internas.- ¿Qué información se coloca en este campo?

2. En la siguiente pestaña, DOCUMENTOS ELECTRÓNICOS:
Firma Electrónica.- ¿Se coloca un nombre cualquiera?
Tipo de emisión.- ¿Qué significa cada alternativa?

Gracias de antemano por su gentil ayuda.

**Comment by Manzarena** [comment]
Buen día,

Estoy en la misma opción, que registro en el campo Firma Electrónica? En la base esta como string el campo

**Comment by ocurieles** [comment]
Coloca la ruta del archivo del certificado Ej. /opt/nombrecertificado.p12

Saludos.

**Comment by Manzarena** [comment]
Muchas gracias.

**Comment by rlguerrero888** [comment]
Gracias.
