### ISSUE TITLE
Firma electrónica y tipo de certificado digital en Odoo V10

### ISSUE THREAD

**Issue by rlguerrero888** [odoo-ecuador/odoo-ecuador#213]
Buenas noches,
en otra consulta me aclararon que el certificado a utilizar para la facturación electrónica debía ser del tipo Roaming. Un funcionario del Banco Central me advirtió hoy que este tipo de certificado causa que cada 25 minutos se desconecte y se deba volver a ingresar los parámetros, por temas de seguridad. ¿Es esto cierto? ¿Se debe utilizar otro tipo de certificado? o ¿El sistema se encarga de mantener siempra activa la sesión/conexión/servicio? 
Necesito facturar (factura electrónica) desde el PoS directamente con Odoo V10. Alguna sugerencia? son bienvenidas.
Gracias de antemano.

**Comment by ocurieles** [comment]
Hola yo he utilizado el certificado de archivo que tiene una clave unica, nunca he tenido que cambiar parametros en ninguno

Saludos

**Comment by rlguerrero888** [comment]
Estimado ocurieles, 
muchas gracias. Parece que me va tocar cambiar nuevamente en el BCE.

**Comment by rlguerrero888** [comment]
Gracias Ocurieles,
Una pregunta adicional. ¿El ATS no lo encuentro, en qué parte se genera o descarga?

**Comment by ovnicraft** [comment]
El certificado en archivo es la solucion adecuada.
El ATS ahora esta en nuestra versión enterprise.
