### ISSUE TITLE
Facturación Electrónica Odoo v10

### ISSUE THREAD

**Issue by rlguerrero888** [odoo-ecuador/odoo-ecuador#215]
Al momento de intentar validar la factura electrónica el sistema indica que se debe crear el establecimiento.

Creo un establecimiento del siguiente modo:

- Documento electrónico: check
- Tipo de comprobante: factura
- Tipo interno: Externas
- Empresa: selecciono la empresa.
- Secuencia: Facturas del cliente.
- Establecimiento: 001-001
-

Me genera el siguiente error:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/odoo-ecuador/l10n_ec_authorisation/models/authorisation.py", line 106, in create
    seq = self.env['ir.sequence'].create(sequence_data)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 132, in create
    _create_sequence(self._cr, "ir_sequence_%03d" % seq.id, values.get('number_increment', 1), values.get('number_next', 1))
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 18, in _create_sequence
    cr.execute(sql, (number_increment, number_next))
  File "/odoo/odoo-server/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
DataError: START value (0) cannot be less than MINVALUE (1)

**Comment by Manzarena** [comment]
Buen día,
Al realizar las pruebas observe que debe registrar todos los datos, es decir también los campos que se muestran cuando no esta marcado el estado que indica si es electrónico. Ya que el error se produce cuando en la secuencia del comprobante se deja 0 en el inicio y 0 en el fin. 

Al guardar de nuevo vuelve a marcar el estado si es electrónico y no se presenta el error.

**Comment by rlguerrero888** [comment]
Gracias Manzarena. Ya lo apliqué.
Ahora al momento de validar la factura tengo el mensaje que indica que debo
seleccionar el establecimiento, pero no aparece en el combo box y no puedo
completar el proceso.

El 2/2/2018 10:48, "Manzarena" <notifications@github.com> escribió:

Buen día,
Al realizar las pruebas observe que debe registrar todos los datos, es
decir también los campos que se muestran cuando no esta marcado el estado
que indica si es electrónico. Ya que el error se produce cuando en la
secuencia del comprobante se deja 0 en el inicio y 0 en el fin.

Al guardar de nuevo vuelve a marcar el estado si es electrónico y no se
presenta el error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/odoo-ecuador/odoo-ecuador/issues/215#issuecomment-362603936>,
or mute the thread

**Comment by rlguerrero888** [comment]
Gracias @Manzarena. Ya lo apliqué.
Ahora al momento de validar la factura tengo el mensaje que indica que debo
seleccionar el establecimiento, pero no aparece en el combo box y no puedo
completar el proceso.

**Comment by rlguerrero888** [comment]
En cada ocasión que intento crear el establecimiento, guardo, pero desaparece. Seleccioné el campo secuencia: factura de cliente.

Intento estableciendo en el campo secuencia:secuencia facturas electrónicas, numero de autorizacion 0, secuencia comprobante 1, 1, establecimiento 002, 001
Al guardar me arroja el siguiente mensaje: La relación de autorización, serie entidad, serie emisor y tipo, debe ser única.

**Comment by ovnicraft** [comment]
Revisar la fecha de validez, el registro se desactiva cuando esta  es menor al dia actual.

**Comment by Manzarena** [comment]
Si tengo creada una autorización pero ya esta asignada al diario Factura de Cliente que esta configurado tipo Venta, ahora le asigno al diario POS Sale Journal la misma autorización pero me crea automaticamente un nuevo secuencial y me sale el mismo error al validar la factura en el POS.

**Comment by Gio666** [comment]
¿con nuevo secuencial a qué te refieres? ¿sale algo como 001001000000003 001001000000004? a mí primero me salían 2 números de factura en una sola, pero creo que ya resolví.

**Comment by Manzarena** [comment]
Si me salen dos y hasta tres números.  Podria compartir el arreglo que hizo?

**Comment by GioViz88** [comment]
No sirvió., sigue el problema, creo que la falla es backend.

**Comment by picassofb** [comment]
Alguien pudo resolver esto? tengo el mismo inconveniente.

**Comment by GioViz88** [comment]
Creo que tiene que ver con el campo num_end, no me dejaba crear establecimientos hasta que puse un valor distinto en ese campo.

**Comment by abdufarag** [comment]
Yo arreglo con Entra todos los datos primero :
Nro. de Autorizacion 
Fetcha de Vencimiento
Sequencia de 1-999999
y guadar 
dispues yo tocar el checkbox Es Documento Electronica ? 
Y ahorita es vale

**Comment by marcopgordillo** [comment]
Ahora el momento de crear una factura se intenta seleccionar un Establecimiento y se desaparece automaticamente. Y se obtiene el error: Los siguientes campos son invalidos Establecimiento

**Comment by elgabo82** [comment]
Amigos, ahora al querer generar una factura electrónica (con todo configurado previamente, archivo de firma, clave, diario de facturación, etc.) tengo el siguiente error o errores:

 File "/home/odoo/.local/share/Odoo/addons/10.0/l10n_ec_einvoice/models/einvoice.py", line 184, in action_generate_einvoice
    access_key, emission_code = self._get_codes(name='account.invoice')
  File "/home/odoo/.local/share/Odoo/addons/10.0/l10n_ec_einvoice/models/edocument.py", line 121, in _get_codes
    ak_temp = self.get_access_key(name)
  File "/home/odoo/.local/share/Odoo/addons/10.0/l10n_ec_einvoice/models/edocument.py", line 109, in get_access_key
    tcomp = utils.tipoDocumento[auth]
KeyError: False

¿Qué debo corregir? ¿Qué hace falta? Espero puedan ayudarme con éste tema.

**Comment by ovnicraft** [comment]
@elgabo82 la autorizacion en el diario de venta no esta configurada.

**Comment by elgabo82** [comment]
Pues está configurada
![imagen](https://user-images.githubusercontent.com/44560472/62404635-3e192f00-b55b-11e9-9305-4e516d9c84db.png)

Obviamente está marcada la casilla de documento electrónico.

![imagen](https://user-images.githubusercontent.com/44560472/62404659-71f45480-b55b-11e9-848f-2c2d5f6bfc3a.png)

Está configurado el P12, la clave, el ambiente (en este caso de Pruebas), etc... y el problema persiste; ¿Qué debo corregir? Disculpas por la insistencia..

**Comment by oskr1087** [comment]
@elgabo82 el tipo de comprobante de ser "Documentos autorizados utilizados en ventas excepto N/C N/D", el tipo "Facturas" es para compras y activa "Documento Electronico?"

**Comment by elgabo82** [comment]
Gracias, pero ahora tengo el error siguiente: 
![Pantallazo-2019-08-05 18-26-54](https://user-images.githubusercontent.com/44560472/62501074-b3c90900-b7ae-11e9-86e0-c51d1bfb4ebd.png)

Y al cliente lo pongo tanto como contribuyente especial o también no obligado a llevar contabilidad y pues sale esa advertencia... ¿Qué más hago?

Disculpas por la torpeza... :\

**Comment by elgabo82** [comment]
Luego de la ayuda estoy teniendo el problema siguiente...
![Pantallazo-2019-08-05 19-39-25](https://user-images.githubusercontent.com/44560472/62503308-39ea4d00-b7b9-11e9-88ff-b5dca3df7210.png)

¿Acaso no está accediendo al PCKS12?

**Comment by elgabo82** [comment]
Problema con el Java resuelto... Ahora estoy con un error de los impuestos...
![Pantallazo-2019-08-05 23-18-13](https://user-images.githubusercontent.com/44560472/62511136-dcb1c400-b7d7-11e9-951a-e97e2fd32e85.png)

**Comment by elgabo82** [comment]
Los impuestos (401) están configurados al 12%; y sigo teniendo el error anterior... 52 ERROR EN DIFERENCIAS

**Comment by RagvDest** [comment]
Buenas
Tengo un problema similar a uno mencionado arriba

> Gracias @Manzarena. Ya lo apliqué.
> Ahora al momento de validar la factura tengo el mensaje que indica que debo
> seleccionar el establecimiento, pero no aparece en el combo box y no puedo
> completar el proceso.

De igual manera, en el momento de validar una factura debo selecciona un Establecimiento del ComboBox, este sí aparece y selecciono una opción pero inmediatamente dicha opción "desaparece" de la casilla. Todo queda como si no hubiera seleccionado nada.
¿A qué se debe este error y cómo podría solucionarlo? Muchas gracias

**Comment by RagvDest** [comment]
Añadir a https://github.com/odoo-ecuador/odoo-ecuador/issues/215#issuecomment-530045034
Revisé y volví a probar las recomendaciones de arriba. 
Gracias, ya lo resolví. 
El problema fue por el Diario, estaba usando uno por defecto que por alguna razón provocaba lo antes expuesto. Así que creé un nuevo Diario y se solucionó.

**Comment by ovnicraft** [comment]
Con los comentarios existentes se puede solucionar este issue.
