### ISSUE TITLE
Problema creación establecimiento y secuencia

### ISSUE THREAD

**Issue by Manzarena** [odoo-ecuador/odoo-ecuador#216]
Por favor me podrían guiar en el orden de crear establecimiento, cuando es electrónico y que secuencial que debe tomar??

**Comment by rlguerrero888** [comment]
# @Manzarena por favor me puedes escribir por whatsapp al +593992601294 ?
Gracias

**Comment by ovnicraft** [comment]
Se resolvio ?
Tratemos de llevar el detalle de soluciones para dejarlo como log para futuras personas que tengan los mismo inconvenientes.

**Comment by Manzarena** [comment]
Buen dia,

Aun tengo problemas porque al validar la factura ahora me muestra dos numeraciones. No entiendo el orden en que debo crear estos datos para que no muestre error, porque en el POS incluso ni valida la factura porque me muestra error.

**Comment by ovnicraft** [comment]
Tienes problemas en validar una factura de cliente o de proveedor ? 
Si es de cliente, el problema esta en el backend o desde el POS ? 
Puedes detallar si tienes la configuracion en los diarios realizada?

**Comment by Manzarena** [comment]
Buen dia,

Si tengo creada una autorización pero ya esta asignada al diario Factura de Cliente que esta configurado tipo Venta, ahora le asigno al diario POS Sale Journal la misma autorización pero me crea automaticamente un nuevo secuencial y me sale el mismo error al validar la factura en el POS.

**Comment by jmurillo77** [comment]
Ya esta configurada pero no veo ningún mensaje de error ni datos en la Clave de acceso o la Autorización, Alguna idea de que mas falta..?
Donde se configuran los directorios para guardar los xml?
Estoy configurando en Windows 10

![image](https://user-images.githubusercontent.com/15874843/36928774-df3ded50-1e56-11e8-8df8-58f044d0f8f0.png)

**Comment by jmurillo77** [comment]
Configure la secuencia, activando modo desarrollador y dirigiéndome a:
- Configuración
- Secuencias e identificadores
- Secuencia
Con esto se me activo el botón de Generar Doc. Electrónico.

Pero ahora tengo el siguiente mensaje de error:
File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\l10n_ec_einvoice\models\edocument.py", line 108, in get_access_key
 AttributeError: 'bool' object has no attribute'type_id'

alguna idea del error?

**Comment by jimmyec** [comment]
Buenas noches
Por favor me pueden indica porque me sale este mensaje de error 
ProgrammingError: el operador no existe: integer = boolean
LÍNEA 1: SELECT number_next FROM ir_sequence WHERE id=False FOR UPDAT...
                                                     ^
SUGERENCIA:  Ningún operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explícitas de tipos.

Al tratar de VALIDAR LA FACTURA desde el punto de venta, después de seleccionar el producto, cliente, pago 

Gracias

**Comment by ovnicraft** [comment]
@jmurillo77 En el branch de 10.0 no esta integrado el POS directo con facturación electronica

**Comment by picassofb** [comment]
@jmurillo77 Como configuraste la secuencia?? Tengo el mismo problema.

**Comment by sperezh2017** [comment]
Problema con la instalación del proyecto, no he logrado instalarlo. y quisiera saber tambien si puedo personalizar el código por lo que me faltan algunos requerimientos para que me cumpla con mi objetivo final. Muchas gracias a todos lo que me puedan aportar algo para mi solucion.

**Comment by ovnicraft** [comment]
@sperezh2017 claro que puedes personalizarlo, recomiendo que si esas mejoras pueden servirnos a todos puedes abrir un PR y mejorar el codigo.

Acerca de pull requests: https://help.github.com/en/articles/about-pull-requests
