### ISSUE TITLE
TaxBase en Facturación electrónica

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#217]
Hola, estoy configurando la FE, al enviar al SRI la factura me devuelve un error de taxBase revisando el codigo encuentro lo siguiente:

totalConImpuestos = []
        for tax in invoice.tax_line_ids:
            if tax.group_id.code in ['vat', 'vat0', 'ice']:
                totalImpuesto = {
                    'codigo': utils.tabla17[tax.group_id.code],
                    'codigoPorcentaje': utils.tabla18[tax.percent_report],
                    'baseImponible': '{:.2f}'.format(tax.base),
                    'tarifa': tax.percent_report,
                    'valor': '{:.2f}'.format(tax.amount)
                    }
                totalConImpuestos.append(totalImpuesto)

El tax.base en la tabla account_invoice_tax viene null y me da diferencias al enviar al SRI, le hice un update a ese campo con la base y me autorizó, alguien ha visto este error ?

**Comment by phoenixgus87** [comment]
Si no estoy mal tienes que habilitar el campo base en tu factura para que se pueda almacenar la base de la factura.

**Comment by picassofb** [comment]
@phoenixgus87 Como haces eso?

**Comment by ovnicraft** [comment]
@ocurieles  es posible crees un PR con tus cambios para mejorar la localizacion.

**Comment by picassofb** [comment]
Tuve el mismo inconveniente y no encontré como habilitar el campo base como sugirieron en un comentario anterior, así que realice el update al generar el documento electrónico. Tal vez alguien pueda tener una mejor solución.

    def action_generate_einvoice(self):
        """
        Metodo de generacion de factura electronica
        TODO: usar celery para enviar a cola de tareas
        la generacion de la factura y envio de email
        """
        sql = "update account_invoice_tax set base=%s where invoice_id=%s" % (
            self.amount_untaxed,
            self.id
        )
        self.env.cr.execute(sql)

**Comment by ovnicraft** [comment]
Sin conocer en que version estas trabajando, no recomiendo hacer un update de ese tipo.
Desde la version 9 odoo cambio el campo base de impuestos aplicado a computed, por lo que recomiendo revisar ese metodo en el objeto y hacer una redefinicion del mismo.
