### ISSUE TITLE
Consulta: cómo configuro la Facturación electrónica en odoo 10

### ISSUE THREAD

**Issue by jomiceve** [odoo-ecuador/odoo-ecuador#218]
saludos estimad@s, por favor estoy tratando de configurar la FE en odoo 10, ya he puesto el PATH o ruta de mi archivo pk12 que se encuentra en el servidor, y he agregado el password de la firma, cúal sería el seguiente paso?, pregunto ya que en el REPO firma/ hay un archivo firmaXadesBes.jar y en el archivo leame indica que:

Se debe copiar el jar conjuntamnete con las librerias que se encuentran en
la carpeta /lib ---> ¿Dónde se encuentra específicamente esa carpeta?

Para ejecutar el proyecto desde la línea de comandos, escriba lo siguiente:

java -jar firmaXadesBes.jar arg1 arg2 arg3   -----> ¿...?

Donde los argumentos son los siguientes:

* arg1: xml en formato cadena.
* arg2: ubicación de la firma electrónica encriptada en base64
* arg3: clave de la firma electrónica encriptada en base64

Gracias de antemano...

**Comment by phoenixgus87** [comment]
Saludos amigo lo que explica en el archivo leame es para desarrolladores, de ahi lo unico que tienes que configurar es la ruta a tu archivo pk12 y la clave.

**Comment by jomiceve** [comment]
Gracias amigo phoenixgus87... una cosita más, asumo que el sistema de FE al ser una aplicación java, en el server donde se encuentra el odoo, debe tener instalado la máquina virtual de java..... saludo y gracias de antemano

**Comment by phoenixgus87** [comment]
Exactamente amigo debe estar instalado la maquina virtual de java en el servidor donde este instalado odoo, ya que el firmado se lo hace a traves del .jar, puedes revisar eso en el modulo l10n_ec_einvoice en el archivo xades.py.

def sign(self, xml_document, file_pk12, password):
        """
        Metodo que aplica la firma digital al XML
        TODO: Revisar return
        """
        xml_str = xml_document.encode('utf-8')
        JAR_PATH = 'firma/firmaXadesBes.jar'
        JAVA_CMD = 'java'
        firma_path = os.path.join(os.path.dirname(__file__), JAR_PATH)
        command = [
            JAVA_CMD,
            '-jar',
            firma_path,
            xml_str,
            base64.b64encode(file_pk12),
            base64.b64encode(password)
        ]
        try:
            logging.info('Probando comando de firma digital')
            subprocess.check_output(command)
        except subprocess.CalledProcessError as e:
            returncode = e.returncode
            output = e.output
            logging.error('Llamada a proceso JAVA codigo: %s' % returncode)
            logging.error('Error: %s' % output)

        p = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )
        res = p.communicate()
        return res[0]

**Comment by ovnicraft** [comment]
En los issues existen ya respuesta para resolver este problema.
