### ISSUE TITLE
Error al crear estableciemiento odoo-ecuador

### ISSUE THREAD

**Issue by steven19734** [odoo-ecuador/odoo-ecuador#221]
Saludos cordiales
Disculpen, tengo el siguiente problema:
He instalado los módulos del repositorio odoo-ecuador. Ya tengo la firma digital (en token) y quiero probar estos para facturación electrónica.
Cuando quiero Validar una factura me solicita que llene el cuadro "Establecimiento" el cual tiene un lista desplegable en blanco como se ve en la imagen
![1](https://user-images.githubusercontent.com/33647557/36827476-c0c0cb48-1ce1-11e8-92c0-8f9a854f50fe.JPG)

Voy a configuración/estableciemiento relleno el formulario y aparecen estos errores:
![2](https://user-images.githubusercontent.com/33647557/36827654-ea64e762-1ce2-11e8-918f-65c33c92886c.JPG)

a que se puede deber esto??
Espero me puedan ayudar. Muchas gracias

**Comment by ovnicraft** [comment]
Debes configurar en el diario de venta el establecimiento y eso se cargara automaticamente en la factura.

**Comment by steven19734** [comment]
Muchas gracias por su pronta respuesta.
Justamente eso hago:
![4](https://user-images.githubusercontent.com/33647557/36850781-a0da1196-1d35-11e8-94dc-4a9b4d6df6b6.JPG)
ingreso un establecimiento:
![5](https://user-images.githubusercontent.com/33647557/36850827-bb94413c-1d35-11e8-88b6-40b5fed0b67f.JPG)
![6](https://user-images.githubusercontent.com/33647557/36850852-c96db3a6-1d35-11e8-885f-233db07aa55d.JPG)

al final al volver a validar la factura ese campo "estableciemiento" sigue sin mostrarlo"
![7](https://user-images.githubusercontent.com/33647557/36850905-e3ac44b2-1d35-11e8-8842-505326bb8f40.JPG)

**Comment by ovnicraft** [comment]
Ahora ese establecimiento debes asignarlo al diario de venta.

**Comment by abdufarag** [comment]
NO PUEDO CREAR ESTABLECIMIENTO , 

1. 
![imagen](https://user-images.githubusercontent.com/5565144/53309173-6302cb00-3874-11e9-878a-6ccd3a389cd4.png)
2. 
![imagen](https://user-images.githubusercontent.com/5565144/53309184-73b34100-3874-11e9-8a20-85faec18c360.png)
3.
![imagen](https://user-images.githubusercontent.com/5565144/53309200-86c61100-3874-11e9-8d9c-b0b3aad2efea.png)
4.
![imagen](https://user-images.githubusercontent.com/5565144/53309208-97768700-3874-11e9-8441-3e65bcc44a0f.png)
5.
![imagen](https://user-images.githubusercontent.com/5565144/53309217-a6f5d000-3874-11e9-88e9-8b8fd7c43877.png)
6. 
![imagen](https://user-images.githubusercontent.com/5565144/53309242-c987e900-3874-11e9-968c-28eca9ca4d59.png)
