### ISSUE TITLE
Periodos en odoo 10

### ISSUE THREAD

**Issue by jomiceve** [odoo-ecuador/odoo-ecuador#222]
Buenas noches... Alguien por favor me podría indicar como se está manejando el tema de los periodos Contables en la versión de Odoo 10, ya que en la versión 8 existe ese menú pero en la versión 10 no la encuentro.

Gracias...

**Comment by ovnicraft** [comment]
En versión 10 se elimino el concepto de periodos, puedes revisar modulos de OCA (date_range) que te permite hacer filtros por rangos de fecha.
