### ISSUE TITLE
Habilitación Botón Factura Electrónica 

### ISSUE THREAD

**Issue by picassofb** [odoo-ecuador/odoo-ecuador#223]
Buenas! Gracias por su excelente aporte a la comunidad. Estoy tratando de hacer funcionar la facturación electrónica en Odoo10, ya puse en compañía la ruta completa de la firma con su respectiva clave y configure los diarios de ventas con sus respectivos establecimientos; puedo realizar la factura pero no me aparece ninguna opción para autorizarla. 
Me falta algo por hacer?? Apreciaría mucho su ayuda.

![image](https://user-images.githubusercontent.com/16357432/39965240-de43b3bc-565a-11e8-8520-6d0d1948b35f.png)

**Comment by ovnicraft** [comment]
La validaste ya ?, debe estar validada para que veas el boton de generar documento electronico

**Comment by picassofb** [comment]
Está validada, y no me genera ningún error al hacerlo. 

![image](https://user-images.githubusercontent.com/16357432/40095306-e79e542a-5890-11e8-9bee-8b811bec062f.png)

**Comment by ovnicraft** [comment]
Esta en estado pagada, en ese estado no se muestra el boton, debe estar en estado Abierto.

**Comment by picassofb** [comment]
Cuando presiono Validar va directo de Borrador a Pagado, como puedo cambiar a abierto?
