### ISSUE TITLE
registro de pagos

### ISSUE THREAD

**Issue by edwinking** [odoo-ecuador/odoo-ecuador#224]
Buenas tardes disculpen estoy probando el soft, la pregunta es al tratar de registrar un pago me aparece el mensaje : "Las entradas no son de la misma cuenta" por favor me podrian indicar como solucionar esto. Gracias y felicitaciones x el trabajo

**Comment by ovnicraft** [comment]
@edwinking puedes agregar capturas de pantalla? aunque no es un issue relacionado a la localización te podemos apoyar en solucionarlo.
