### ISSUE TITLE
Secuencias de Retenciones

### ISSUE THREAD

**Issue by GioViz88** [odoo-ecuador/odoo-ecuador#226]
¿hay forma de configurar las secuencias de retenciones?

Estoy probando las retenciones, he conseguido que tome los valores de serie_entidad, serie_emisión y el dígito siguiente de la secuencia, pero cuando creo una nueva retención, no me aumenta la secuencia. 

![screenshot from 2018-06-12 16-41-11](https://user-images.githubusercontent.com/7320979/41318872-78258390-6e5f-11e8-8886-b694335df90f.png)

La retención 001001000000145 fue ingresada manualmente y funcionó bien,
Las otras retenciones con el mismo número 001001000000000 se les generó el número automáticamente en base a la secuencia. Como ven, el problema es que la secuencia no aumentó.

**Comment by ovnicraft** [comment]
@Gio666  Que version de software estas usando ?
Debes configurar en el diario de compra la secuencia de retenciones.

**Comment by GioViz88** [comment]
es la 10, ya resolví, noté que al validarla se generaba la secuencia.
