### ISSUE TITLE
l10n_ec-invoice_sequence: dependencia inexistente

### ISSUE THREAD

**Issue by miltonlab** [odoo-ecuador/odoo-ecuador#23]
El modulo l10n_ec-invoice_sequence requiere el módulo inexistente 'retention'

**Comment by ovnicraft** [comment]
Aca el error https://github.com/odoo-ecuador/odoo-ecuador/blob/7.0/l10n_ec-invoice_sequence/__openerp__.py#L28

**Comment by ovnicraft** [comment]
@miltonlab tienes un PR o lo corregimos aca ?

**Comment by ovnicraft** [comment]
Corregido en el PR https://github.com/odoo-ecuador/odoo-ecuador/pull/39

**Comment by ovnicraft** [comment]
@miltonlab quedo pendiente de revision para cerrar el bug :-)

**Comment by miltonlab** [comment]
estoy un poco confundido, entendí anteriormente que este módulo ya no se necesitaba?, por eso lo eliminé en la 8.0 !!!

**Comment by ovnicraft** [comment]
si, ya no se lo necesita pero estoy haciendo una transicion para eliminarlo, si lo has eliminado en la 8 y pones los cambios que he realizado en la 7, no habra problema.

**Comment by ovnicraft** [comment]
Se corrigio en favor de https://github.com/odoo-ecuador/odoo-ecuador/tree/7.0/l10n_ec_invoice_sequence
