### ISSUE TITLE
Detalles de pago de la factura no desglosa según si el producto aplica o no impuesto IVA 

### ISSUE THREAD

**Issue by jomiceve** [odoo-ecuador/odoo-ecuador#230]
Hola Amigos... al imprimir la factura en odoo 10, en la sección de los montos a pagar, me puedo dar cuenta que no se desglosa los montos que aplican IVA y los que no aplican, y solo se muestra en el campo  Subtotal 0%, a pesar de que tengo productos con iva y sin iva... no se si sera por problemas de configuración o es un bak de la localización.... gracias de antemano por la ayuda

**Comment by ovnicraft** [comment]
Puede agregar una captura de pantalla de lo mencionado. ?
