### ISSUE TITLE
Generación de Factura tradicional y electrónica desde POS

### ISSUE THREAD

**Issue by cjcruz** [odoo-ecuador/odoo-ecuador#236]
Hola! Cuando realizo una venta con el POS genero 2 documentos, un recibo sin validez tributaria y una factura en estado abierta, el recibo lo imprimo para que los clientes lo tengan como comprobantes de su compra mientras se espera que un usuario ejecute manualmente la obtención de los documentos electrónicos con el SRI para la factura generada. 
¿Es este el flujo que se debe seguir con la localización odoo-ecuador de este repositorio? 
¿Hay algún módulo para generar desde el POS, la creación de la factura, obtención de documentos electrónicos y mover la factura a estado pagado automáticamente cuando se presione el botón de "validar" en el POS?

Gracias de antemano.

Christian.

**Comment by ovnicraft** [comment]
@cjcruz debes activar el POS para facturacion.
Comentanos que version de odoo usas y detallar mas sobre la configuracion de tu POS.

**Comment by cjcruz** [comment]
> @cjcruz debes activar el POS para facturacion.
> Comentanos que version de odoo usas y detallar mas sobre la configuracion de tu POS.

Estoy usando la versión 10 de Odoo, tengo instalado el modulo POS de fábrica y el modulo l10n_ec_pos de este repositorio.   Para mi caso de uso en particular, el modelo de negocios genera pocas facturas y quisiera habilitar que el POS envíe los requerimientos de facturación electrónica al SRI cuando se presione el botón "validar" del POS.

sAludos..

**Comment by ovnicraft** [comment]
Requiere una personalización la cual no esta disponible al momento en el repositorio.
