### ISSUE TITLE
Problema al Generar Documento Electrónico Odoo v10

### ISSUE THREAD

**Issue by elgabo82** [odoo-ecuador/odoo-ecuador#238]
Amigos, ahora al querer generar una factura electrónica (con todo configurado previamente, archivo de firma, clave, diario de facturación, etc.) tengo el siguiente error o errores:

File "/home/odoo/.local/share/Odoo/addons/10.0/l10n_ec_einvoice/models/einvoice.py", line 184, in action_generate_einvoice
access_key, emission_code = self._get_codes(name='account.invoice')
File "/home/odoo/.local/share/Odoo/addons/10.0/l10n_ec_einvoice/models/edocument.py", line 121, in _get_codes
ak_temp = self.get_access_key(name)
File "/home/odoo/.local/share/Odoo/addons/10.0/l10n_ec_einvoice/models/edocument.py", line 109, in get_access_key
tcomp = utils.tipoDocumento[auth]
KeyError: False

¿Qué debo corregir? ¿Qué hace falta? Espero puedan ayudarme con éste tema.

- Odoo v10 clonado usando git en Ubuntu 16.04

**Comment by elgabo82** [comment]
Tengo configurado el respectivo plan de cuentas, la autorización en el diario, el archivo p12 con su clave, las dependencias, y demás etcéteras... ¿Qué debo corregir? ¿Qué falta por hacer?...

**Comment by ovnicraft** [comment]
En otro issue esta superado este problema

**Comment by elgabo82** [comment]
Sigue el tema, ahora tengo el error 52 de diferencias, en la tabla account_invoice_tax, el campo "base" está en null y sólo cuando se actualiza de forma manual con el valor de la base de la factura, ahí es posible iniciar la autorización y emisión del documento electrónico.

¿Dónde debo corregir el tema?

**Comment by ovnicraft** [comment]
Puedes revisar el calculo de impuestos en la redefinicion de metodo _compute_ en donde se calcula y asignan estos valores.
