### ISSUE TITLE
ENVIÓ DOCUMENTOS EN AMBIENTE DE PRUEBAS

### ISSUE THREAD

**Issue by phoenixgus87** [odoo-ecuador/odoo-ecuador#240]
De pronto a alguien le sucedió que ambiente de pruebas esta dando este error "39 FIRMA INVALIDA ERROR El certificado utilizado, no es del tipo firma digital", pero en ambiente de producción todo funciona correctamente.

**Comment by mamfredym** [comment]
Justo hoy el SRI envió un comunicado con respecto a ese tema.

Dentro de una firma electrónica existen por llamarlos así "TIPOS DE FIRMAS" o "TIPOS DE FIRMADOS". El tipo de firmado que debe darse al XML es de tipo **“Firma digital (Digital Signature)”**  y la verdad no se si el jar que esta [aquí](https://github.com/odoo-ecuador/odoo-ecuador/tree/10.0/l10n_ec_einvoice/xades/firma) firma usando el Digital Signature.

Según el SRI esa es la validacion que se esta dando.

Tal vez @ovnicraft nos puede ayudar con ese tema.

Saludos

![image](https://user-images.githubusercontent.com/47071819/70836441-1ae67200-1dce-11ea-85cc-139bc988c2f3.png)

**Comment by ovnicraft** [comment]
Quien escribio el jar es @alcidesrivera nos puedes dar feedback al respecto ? 
Que opinas si abrimos un repo con el codigo del jar, asi algun experto en java lo pueda revisar, validar, mejorar :-)

**Comment by ovnicraft** [comment]
@mamfredym tenemos el src de @alcidesrivera aca https://github.com/odoo-ecuador/odoo-ecuador/blob/8.0/l10n_ec_einvoice/xades/firma/src/ec/com/virtualsami/xades_firma/XAdESBESSignature.java

Puedo confirmar que ese `.jar`  da error en el ambiente de pruebas del SRI, retornando el mensaje: 
"El certificado utilizado, no es del tipo firma digital".

We have a critical bug :(

tenemos algun java dev que lo pueda solucionar ?

**Comment by arkhan** [comment]
@ovnicraft aquí tienen como resolver este bug:
https://github.com/rolandopalermo/veronica/commit/8958028270e52359290e86902971bd062c2d9a9c

**Comment by ovnicraft** [comment]
@arkhan genial ! veamos quien se anima a un rebuild y actualizamos el jar

**Comment by ocurieles** [comment]
hola @ovnicraft yo soy JavaDev - yo lo arreglo, incluso ya lo hice en IDempiere.
Te paso el PullRequest cuando lo haga este fin.

 Saludos.

**Comment by ovnicraft** [comment]
@ocurieles estara super bien si sacas el code de la rama 8 y haces PR a https://github.com/odoo-ecuador/xades-signer

Asi tenemos el src alla y cualquier cosa lo mejoramos directo ahi

deal ?

**Comment by ocurieles** [comment]
Seguro, de acuerdo

**Comment by ocurieles** [comment]
Hola gente, ya terminé la migración - alguien que me ayude con las pruebas, hice unas mejoras y cambios que ayudan :) https://github.com/ingeint/xades-signer/tree/master/xades-ec/src

Despues de probar hago el PR.
  Saludos.

**Comment by ocurieles** [comment]
el jar ahora se llama xades-ec-standalone.jar y está en la raíz del proyecto, acabo de hacer commit, para generar un nuevo jar ahora se hace con gradle.

 Saludos y feliz Navidad.

**Comment by ovnicraft** [comment]
Excelente regalo @ocurieles hacer es PR para tenerlo en master ?

**Comment by ovnicraft** [comment]
@ocurieles al ejecutar el jar tengo este error https://gist.github.com/ovnicraft/88d92d8a6af3330ea259d14644cb0f7c

**Comment by ovnicraft** [comment]
JFTR: @alexVma lo resolvio y la rama 10 fue actualizada.
