### ISSUE TITLE
Validacion de RUC

### ISSUE THREAD

**Issue by mamfredym** [odoo-ecuador/odoo-ecuador#241]
Según leido este documento y pruebas que hice con algunos RUC hay algunos casos que considerar.

1._ Cambiar que Tipo de persona un valor seleccionable (selection) en lugar que sea calculado.
2._ Existen RUC que el tercer dígito es el número 6 pero es personal natural. Este caso es de Extranjeros con cédula que han obtenido su RUC. Por lo que el dígito verificador del RUC es el 10mo y no el 9no cómo es un RUC
3._ Existen RUC de personas extranjeras que NO TIENEN cédula. En estos casos el SRI asigna un tercer dígito 9 para este caso, por lo que es RUC de Persona natural con un tercer digito 9 y el digito verificador es el 9no igual que un RUC normal.

Mas info:
https://www.jybaro.com/blog/cedula-de-identidad-ecuatoriana/

**Comment by mamfredym** [comment]
![ced1](https://user-images.githubusercontent.com/47071819/70808832-83adfa00-1d8e-11ea-80ac-5631e899b52a.jpeg)

![ced2](https://user-images.githubusercontent.com/47071819/70808843-89a3db00-1d8e-11ea-8697-bcf4de925b7d.jpeg)

**Comment by ovnicraft** [comment]
Actualmente la recomendacion es usar https://pypi.org/project/python-stdnum/

@mamfredym  Puedes comentar aca mas cedulas/ruc de esos casos para abrir un PR en python-stdnum y mejorar esa lib ?

**Comment by jybaro** [comment]
Hola, en Ecuador no existe forma 100% confiable de validar el RUC solamente con su número, ya que la definición del SRI del dígito verificador del RUC está rota. La estructura interna del número RUC que utiliza el SRI es arbitraria y no fue coordinada con el Registro Civil, por lo que existen casos de números de cédulas y RUC incompatibles cuando hay personas naturales con tercer dígito 6 en su número de cédula. En estos casos, el SRI toma el noveno dígito como verificador (ya que sería RUC de institución pública), mientras que el Registro Civil toma el décimo dígito.

En general, las personas que tienen el tercer dígito 6 viven un calvario en Ecuador, por ejemplo el sistema de salvoconductos para sacar el carro durante el toque de queda no les permite el ingreso. Esto provoca que, para evitar tales injusticias y protegerse contra futuras incompatibilidades, se evite validar el RUC con su dígito verificador, y peor con su estructura interna.

**Comment by ovnicraft** [comment]
@jybaro gracias por tu comentario!, es un honor leerte por aca :)

OT: Me gustaria tengamos contacto interno, estamos implementando BES en Python y tu asesoria nos servira de mucho.
