### ISSUE TITLE
Error con el cambio de firmado actualizacion de JAR

### ISSUE THREAD

**Issue by phoenixgus87** [odoo-ecuador/odoo-ecuador#246]
Buen día he realizado una prueba con la actualización del jar para la firma electrónica pero me ha resultado un par de errores los cuales adjunto de pronto si alguien sabe la solución del error que ayude. Gracias

<img width="538" alt="errorOdoo2" src="https://user-images.githubusercontent.com/34517337/77252792-432f0980-6c24-11ea-9689-ba605480c93e.PNG">

Error: Could not find or load main class odooxadesfirma.OdooXadesFirma

2020-03-22 14:54:51,133 11844 INFO desarrollo requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): celcer.sri.gob.ec

**Comment by renbenj9** [comment]
Saludos

phoenixgus87, se encontró la solución?, porque a mas del error indicado pude hacer una captura de log en donde indica un error desde el firmado. 
Adjunto Pantalla
Si alguien tiene la solución  muchas gracias
![error](https://user-images.githubusercontent.com/17787007/89373766-2d8c1f00-d6af-11ea-86ac-9852e80a71af.png)

**Comment by phoenixgus87** [comment]
Buenas tardes no hubo solución a lo mencionado, en lo que respecta al issue creado, fue porque se realizaba cambios sobre el jar de firmado, ya que al firmar en ambiente de pruebas sale error error "39 FIRMA INVALIDA ERROR El certificado utilizado, no es del tipo firma digital", pero el error sale cuando son firmas electrónicas generadas por el registro civil, esta vez he trabajado con 2 clientes que se saco firma electrónica con la ANF y no tuve esos inconvenientes en ambiente de pruebas, de pronto dejo el contacto de la persona que les puede ayudar a sacar firmas electrónicas en la ANF. Karina Castro 0999454848
