### ISSUE TITLE
continuidad del proyecto

### ISSUE THREAD

**Issue by leyetfz** [odoo-ecuador/odoo-ecuador#249]
El proyecto está descontinuado o podemos desarrollar sobre el mismo:

- Módulo que faltan
- Migración a nuevas versiones de ODOO

Muchas gracias

**Comment by ovnicraft** [comment]
@leyetfz se puede desarrollar sobre el mismo, no es muy activo pero si tiene ciertos aportes.

eres bienvenido para aportar !
