### ISSUE TITLE
Error al generar la factura de proveedor a partir de un pedido de compra

### ISSUE THREAD

**Issue by alcidesrivera** [odoo-ecuador/odoo-ecuador#25]
Al intentar generar una factura de proveedor a partir de un pedido de compra genera el siguiente error:

https://gist.github.com/alcidesrivera/bfb1141de0ac573f44a1#file-log_error

**Comment by ovnicraft** [comment]
El modulo l10n_ec-invoice_sequence ya no es funcional, @miltonlab lo esta por remover.

**Comment by miltonlab** [comment]
ya lo he hecho pero en la rama 8.0, como replico mis cambios de la 8.0 a la 7.0 @ovnicraft?

**Comment by ovnicraft** [comment]
tienes que pasarte a la rama 7.0, git checkout 7.0 y luego hacer merge de la rama 8.0, ojo con esto ya que puede bajarte todo de la 8.0.

Puede ser mejor pasarse a la 7.0 y ahi volver a corregirlo

**Comment by ovnicraft** [comment]
El modulo es necesario para numerar las facturas de forma correcta, esta pendiente terminarlo.
Hay un PR https://github.com/odoo-ecuador/odoo-ecuador/pull/40 pendiente para poder usarlo.

**Comment by miltonlab** [comment]
mmm osea que debo volver  a incluirlo

**Comment by ovnicraft** [comment]
@alcidesrivera pudimos corregir este errror  ?

**Comment by alcidesrivera** [comment]
Corregido
