### ISSUE TITLE
Porque no hacerlo en python puro, es super fácil

### ISSUE THREAD

**Issue by erikn69** [odoo-ecuador/odoo-ecuador#252]
https://github.com/odoo-ecuador/odoo-ecuador/blob/bbaf79c0c024ea4aeb2b548a29ee410c0534c9d2/l10n_ec_einvoice/xades/xades.py#L57

**Comment by ovnicraft** [comment]
@erikn69 nos apoyas con un PR?

**Comment by erikn69** [comment]
No uso odoo, pero haciéndole ingeniería inversa y con la información de https://www.jybaro.com/blog/firma-electronica-de-factura-electronica/ resulta que pyopenSSL tiene un problema al leer las firmas, vienen 6 private keys, y 6 public keys(depende de los años de la firma), lo que se hace es recorrer las public hasta encontrar la que este vigente a la fecha, esa la colocas en el xml y recorres las private keys en busca de la par que contenga ese certificado publico vigente y se firma, con eso ya la firma es válida, ojo para poder recorrer se debe dar un tratamiento al p12 con openssl puro, esto se realiza solo una vez por cada firma, eso lo mencionan en https://www.jybaro.com/blog/soluciones-firma-electronica-xades-bes/
