### ISSUE TITLE
Status Requerimientos

### ISSUE THREAD

**Issue by miltonlab** [odoo-ecuador/odoo-ecuador#26]
Sería bueno colocar el estado en el que se encuentra cada requerimiento aquí o no se si hay otro lugar mas apropiado dentro del repo.

**Comment by codeadict** [comment]
Creo debería ser en la WIKI y poner cada requerimiento referenciado como una issue

**Comment by ovnicraft** [comment]
Estamos generando issues por cada requerimiento.
