### ISSUE TITLE
Generación de Clave de Acceso

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#30]
Las claves de acceso estarán compuestas de 49 caracteres numéricos, la herramienta o 
aplicativo a utilizar por el sujeto pasivo deberá generar de manera automática la clave de 
acceso, que constituirá un requisito que dará el carácter de único a cada uno de los 
comprobantes, y la misma servirá para que el SRI indique si el comprobante es autorizado 
o no; se describe a continuación su conformación: 

TABLA 1 

![captura de pantalla de 2014-11-12 16 14 37](https://cloud.githubusercontent.com/assets/31282/5018703/21b8ca2e-6a87-11e4-8fe5-23d33cfdc2e7.png)

Nota: Todos los campos deben completarse conforme a la longitud indicada, es decir si en el 
número secuencial no completa los 9 dígitos, la clave de acceso estará mal conformada y 
será motivo de rechazo de la autorización en línea. 

El dígito verificador será aplicado sobre toda la clave de acceso (48 dígitos) y deberá ser 
incorporado por el contribuyente a través del método denominado Módulo 11, con un factor 
de chequeo ponderado (2), este mecanismo de detección de errores, será verificado al 
momento de la recepción del comprobante. Cuando el resultado del dígito verificador obtenido 
sea igual a once (11), el digito verificador será el cero (0) y cuando el resultado del dígito 
verificador obtenido sea igual a diez 10, el digito verificador será el uno (1). 

El código numérico constituye un mecanismo para brindar seguridad al emisor en cada comprobante emitido, el algoritmo numérico para conformar este código es potestad absoluta 
del contribuyente emisor. 

Ejemplo de verificación utilizando algoritmo de módulo 11:

![captura de pantalla de 2014-11-12 16 16 28](https://cloud.githubusercontent.com/assets/31282/5018724/522c9f78-6a87-11e4-8d4f-01cb65200ef9.png)

5.4 El código que conformará el tipo de emisión según la clave de acceso generada se detalla
a continuación:

TABLA 2
![tabla2](https://cloud.githubusercontent.com/assets/1406609/5054955/f9cb14a0-6c29-11e4-8798-900dacc7f0fe.png)

5.8 Los tipos de comprobantes que pueden generar los contribuyentes de manera electrónica
se detalla conforme al siguiente cuadro:

TABLA 4
![tabla4](https://cloud.githubusercontent.com/assets/1406609/5054959/035ab890-6c2a-11e4-8311-caa7c0110d38.png)

5.9 El código que conformará el tipo de ambiente según la clave de acceso se cita a
continuación:

TABLA 5
![tabla5](https://cloud.githubusercontent.com/assets/1406609/5054963/0d105a16-6c2a-11e4-996a-4ff21fd169d4.png)

**Comment by ovnicraft** [comment]
@miltonlab Ayudame a revisar si esto esta completo y correcto.

**Comment by miltonlab** [comment]
Te refieres en el código la existente de la localización? o a la teoría que subiste?

**Comment by ovnicraft** [comment]
@miltonlab la teoria, me gustaria que quede super claro y documentado el proceso de facturación electronica.

**Comment by miltonlab** [comment]
OK

**Comment by ovnicraft** [comment]
La clave de acceso es de 49 caracteres segun tabla 1

**Comment by miltonlab** [comment]
@ovnicraft no deberiamos poner este Issue más bien como un milestone? o estoy equivocado?

**Comment by miltonlab** [comment]
Creo que ahora está completo !!!

**Comment by ovnicraft** [comment]
Implementado en https://github.com/odoo-ecuador/odoo-ecuador/pull/48

**Comment by danychaia** [comment]
el Codigo numerico a que se refiere o cual es ese perdon estoy trabajando con su localizacion y no soy ecuatoriano

**Comment by ovnicraft** [comment]
un numero cualquiera de 8 digitos.

**Comment by danychaia** [comment]
Gracias muy amable :)

**Comment by geovanny6** [comment]
La cadena de verificación  en el ejemplo, de donde la obtengo?
Gracias
