### ISSUE TITLE
Migración a la versión 8.0 - creacion de facturas

### ISSUE THREAD

**Issue by miltonlab** [odoo-ecuador/odoo-ecuador#32]
Una vez que odoo-ecuador es instalable en odoo v 8.0, estoy empezando a revisar la funcionalidad, entonces tengo el primer fallo donde espero la ayuda de la comunidad para continuar con la migración:

Al crear una nueva factura este es el resultado:

  File "/home/miltonlab/opt/odoov8/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/miltonlab/opt/odoov8/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/miltonlab/opt/odoov8/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/miltonlab/opt/odoov8/openerp/models.py", line 5709, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/miltonlab/opt/odoov8/openerp/models.py", line 5643, in _onchange_eval
    method_res = getattr(self._model, method)(_args)
  File "/home/miltonlab/opt/odoov8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, *_kwargs)
TypeError: onchange_partner_id() takes at most 10 arguments (11 given)

**Comment by ovnicraft** [comment]
Pensamos en migrar el reporte a qweb @miltonlab ?

**Comment by miltonlab** [comment]
Por ahora no @ovnicraft , solo quiero arreglar las diferencias con respecto a la v8 para que quede funcional y poder concentrar los esfuerzos en la facturación, que pienso sería bueno que esté terminada hasta diciembre, pues en enero la exigencia se amplia a más grupos de contribuyentes.

**Comment by miltonlab** [comment]
Disculpas por el reporte de error, lo he actualizado al correcto

**Comment by miltonlab** [comment]
Corregido

**Comment by Deysy** [comment]
Hola miltonlab quisiera saber que fue lo que isiste para resolver el problema, ya que tambien estoy tratando de migrar a odoo. Gracias

**Comment by miltonlab** [comment]
Básicamente adaptando los parámetros de algunas acciones y llegando hasta este cambio: https://github.com/odoo-ecuador/odoo-ecuador/commit/520f14a7e7b8dc9a758c179bda34b46d2ec0fd14#diff-0
