### ISSUE TITLE
Migración v8.0 - Al agregar item a factura

### ISSUE THREAD

**Issue by miltonlab** [odoo-ecuador/odoo-ecuador#34]
File "/home/miltonlab/opt/odoov8/openerp/models.py", line 5709, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/miltonlab/opt/odoov8/openerp/models.py", line 5643, in _onchange_eval
    method_res = getattr(self._model, method)(_args)
  File "/home/miltonlab/opt/odoov8/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/home/miltonlab/odoo-labs/odoo-ecuador/l10n_ec_withdrawing/withdrawing.py", line 1043, in product_id_change
    company_id = company_id if company_id != None else context.get('company_id',False)
TypeError: 'int' object is not iterable

**Comment by ovnicraft** [comment]
El metodo tiene que ser actualizado a la version 7.0 / 8.0 @miltonlab 
Recuerdo que habias trabajado en eso, podemos resolverlo en conjunto.

**Comment by miltonlab** [comment]
Wow, full actividad Cristian , je je, parece que hay bastante nuevo que
revisar, lo haremos entonces

El 4 de enero de 2015, 2:14, Cristian Salamea notifications@github.com
escribió:

> El metodo tiene que ser actualizado a la version 7.0 / 8.0 @miltonlab
> https://github.com/miltonlab
> Recuerdo que habias trabajado en eso, podemos resolverlo en conjunto.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoo-ecuador/odoo-ecuador/issues/34#issuecomment-68623839
> .

## 

/\/\;/-----------------------------------------------------
Milton  Labanda  [miltonlab]
Distro:        Debian GNU/Linux 6.0 Squeeze
Blog:          http://1000tonlab.wordpress.com
jabber:        miltonlab@jabber.org milotnlab@jabber.org
"... Solamente la libertad que se somete a la Verdad conduce a la persona
humana a su  verdadero bien...".  Karol Wojtyla
(:\ Usa Software Legal, usa Software Libre /:)

**Comment by ovnicraft** [comment]
@miltonlab entro en produccion con un cliente en 3 semanas, desde el miercoles ingresan noviembre y diciembre en el sistema para sacar balances y comparativas.
Vamos a tener una version bastante estables a finales de enero :-)

Tambien vamos con facturacion electronica, tengo un WIP, si alcanzo noche lo subo.

**Comment by miltonlab** [comment]
Que bueno !!!
