### ISSUE TITLE
Problema al instalar Project for Government

### ISSUE THREAD

**Issue by marcopgordillo** [odoo-ecuador/odoo-ecuador#35]
Por favor si me pueden ayudar con el módulo de Odoo-ecuador para la versión 8.0, al querer instalarlo, obtengo el error:

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//div[@name="options_active"]">' cannot be located in parent view

Error context:
View `Inherit project form : Invoicing Data`
[view_id: 1624, xml_id: project_timesheet.project_invoice_form, model: project.project, parent_id: 823]" while parsing /opt/odoo/odoo-ecuador-8.0/l10n_ec_project_gob/view/project_view.xml:234, near
<record id="project.edit_project" model="ir.ui.view">
            <field name="name">project.project.form</field>
            <field name="model">project.project</field>
            <field name="arch" type="xml">
                <form string="Project" version="7.0">

**Comment by ovnicraft** [comment]
nos ayudas con todo el traceback del error. @marcopgordillo
