### ISSUE TITLE
Soporte fiscal

### ISSUE THREAD

**Issue by Jzarecta** [odoo-ecuador/odoo-ecuador#4]
Saludos quiero saber si el modulo ecuatoriano de contabilidad da soporte para impuestos de tipo
ICE = Impuesto a los Consumos Especiales

Y los reportes en formatos:
RDEP = Anexo de Retenciones en la Fuente Bajo Relación de Dependencia
ATS = Anexo Transaccional Simplificado

**Comment by ovnicraft** [comment]
El ICE lo hemos implementado como un impuestos de tipo diferente de IVA.
El rdep no esta implementado.
El ATS esta implementado a la ultima version requerida por el SRI.

**Comment by ovnicraft** [comment]
@Jzarecta puedes probar la version publicada funciona bien para el ATS
