### ISSUE TITLE
Mejorar wiki de instalacion

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#45]

**Comment by ayepezv** [comment]
Saludos, soy nuevo en este mundo de compartir pero me ha gustado mucho el usar odoo, y mejor si podemos mejorarlo y compartir desde mi país, será que se podría explicar un poco más al respecto de estos adds desarrollados, como por ejemplo la forma de implementarlo y como utilizarlo en que apicaciones de odoo se utilizaría. Perdón si no es el lugar adecuado para mi inquietud........

**Comment by ovnicraft** [comment]
@ayepezv Claro podemos ayudarte, tienes muchas dudas en un solo lugar,

La forma e implementarlo es muy amplia depende de tu alcance de proyecto.
La localización esta orientada a tener el área financiera controlada.
