### ISSUE TITLE
Agregar total + iva en linea de factura

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#50]
Se requiere agregar el campo de base imponible mas IVA en la linea de factura.
Es bloqueante para la generacion de facturacion electronica.

**Comment by alcidesrivera** [comment]
No es la base imponible más IVA sino únicamente el valor de IVA por cada línea de factura.

**Comment by ovnicraft** [comment]
@miltonlab FYI

**Comment by ovnicraft** [comment]
Resuelto en https://github.com/ovnicraft/openerp-ecuador/commit/6b96df0a1d4eb51cb408189a05d34846109ad059
