### ISSUE TITLE
Existe algún add o aplicación que permita facturar en Lote, de clientes

### ISSUE THREAD

**Issue by ayepezv** [odoo-ecuador/odoo-ecuador#62]
Soy nuevo usando Odoo, pero veo la potencialidad del desarrollo, tengo una empresa que brinda servicio a varios clientes y a los mismos les facturo mensualmente rubros específicos, ya determinados, el asunto es que son como 105 y debo mensualmente facturarles, de acuerdo a los servicios que tengan contratado, sería ideal les llegue su factura al correo o ya tener aunque sea precargado sus rubros solo para que cuando paguen o acepten el pago se generen y envíe a sus correos; existirá algo similar ya desarrollado o se podría proponer como un desarrollo específico, espero puedan ayudarme de antemano gracias....

**Comment by ovnicraft** [comment]
@ayepezv puedes revisar esto: http://odedrabhavesh.blogspot.in/2014/12/how-to-create-recurring-invoice-in-odoo.html

**Comment by ayepezv** [comment]
Gracias @ovnicraft muy buena tu información, es evidente que dominas este tema, y referente al mismo tema ahora me nació la inquietud, si se podrá hacer con esto mismo lo que ahora nos piden la facturación electrónica de Ecuador, pudiendo enviar a los correos y de igual recibir las que nos envíen y se registren, ya sea poder desarrollarlo o ya existirá para que puedan implementarlo. Y aquí mismo otra pregunta cursos de capacitación para el manejo y / o desarrollo sobre odoo, existe en Ecuador

**Comment by ovnicraft** [comment]
@ayepezv Puede revisar el modulo 1l0n_einvoice que es para la facturación electrónica.
Aún no contamos con la importación de las facturas, podemos abrir un issue para describir el requerimiento.

**Comment by ayepezv** [comment]
Que bien muchas gracias por tu ayuda @ovnicraft, es notorio que conoces bien el tema, voy a revisarlo para poder seguir comentando
