### ISSUE TITLE
actualizar datos de impuestos y codigos de impuestos

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#70]
El primer borrador de archivos:
[Codigos](https://www.dropbox.com/s/dgyrx3jyx9blyld/account.tax.code.csv?dl=0)
[Impuestos](https://www.dropbox.com/s/uph4igrbhq931nf/account.tax.csv?dl=0)

**Comment by ovnicraft** [comment]
@libreec

**Comment by libreec** [comment]
Estuve revisando el archivo y quiero sugerir que en lugar de utilizar números por orden del impuesto en el archivo csv para generar el id de cada item utilicemos el código del impuesto.

Ejemplo:

en lugar de account_tax15 para el código de impuestos 302, podemos utilizar account_tax_302

Otra opción que he visto util en mis localizaciones es incrementar el año de aplicación del impuesto, por ejemplo account_tax_3022015 pues así, si hay cambios para el próximo año se puede cambiar el impuesto account_tax_3022015 a inactivo y crear uno nuevo account_tax_3022016 y podemos aplicar los cambios de la administración tributaria sin mayores complicaciones.

**Comment by libreec** [comment]
Otra sugerencia que tengo es la de crear archivos independientes por formulario.

Un csv para el formulario 103, otro para el formulario 104 y así, especialmente en los formularios grandes como los mencionados. 

Así vamos a poder tener claridad en los impuestos que se configuran y da mayor facilidad para la lectura y modificación del documento para el futuro.
