### ISSUE TITLE
Imprimir Recibo en Cocina con pos_restaurant

### ISSUE THREAD

**Issue by alcidesrivera** [odoo-ecuador/odoo-ecuador#71]
Al intentar configurar la siguiente impresora fiscal en la cocina  067b:2303 Prolific Technology, Inc. PL2303 Serial Port

da el error: https://gist.github.com/alcidesrivera/81fa913c698971ab6bfb

Lo que provoca que no se logre imprimir el recibo

**Comment by ovnicraft** [comment]
No hemos tenido mayor detalle al respecto, voy a cerrar el issue.
