### ISSUE TITLE
Manual de Uso Localización Ecuador

### ISSUE THREAD

**Issue by ocurieles** [odoo-ecuador/odoo-ecuador#77]
Hola, primeramente los felicito por colaborar con código a esta comunidad de Ecuador, vengo de iDempiere donde aportamos bastante código fuente y quería saber si para la localización odoo Ecuador tienen alguna guía de instalación o alguna wiki que explique paso a paso la configuración, tengo algunos vacíos, por ejemplo no se si es posible generar retenciones automáticamente de ser afirmativo como puedo configurarlas, por otra parte si posee un módulo de facturación electronica, si alguien puede ayudarme con ese requerimiento y si tiene algún costo estamos dispuesto a apoyar para publicarlo en ese sitio o en una wiki.

 Quedo atento.

**Comment by ovnicraft** [comment]
Que tal, a breve lectura considero que tenemos todo lo que requieres, sin embargo wiki no hay.
Podrias crear una y en base a comentarios puedes consolidar esa info y ponerle en la wiki, nos ayudaria un monton ! @ocurieles, si deseas dale !

**Comment by ocurieles** [comment]
Hola, Gracias por responder.. con todo gusto podemos hacer el aporte a la comunidad, solo necesitamos aclarar algunas dudas, no se si tal vez podrías apoyarnos con una hora de consultoría puntual para lo que nos falta configurar, si tiene costo no tenemos problema en cancelarlo y ahi nos quedaría ya la pagina de la wiki.

 Te adjunto algunos de nuestros aportes a iDempiere

 http://wiki.idempiere.org/en/Plugin:_Scale_Connector

http://wiki.idempiere.org/en/Category:Available_Plugins

   Muy agradecido por tu respuesta
