### ISSUE TITLE
Fallo al instalar en ODOO V8 l10n_ec_partner

### ISSUE THREAD

**Issue by cholitoecuatoriano** [odoo-ecuador/odoo-ecuador#79]
Al instalarlo en una instalación fresca la consolo muestra el siguiente mensaje:

openerp.models: WARNING: unable to set column ced_ruc of table res_partner not null !

**Comment by ovnicraft** [comment]
@cholitoecuatoriano el warning se genera por que la compania genere un registro partner y al no estar ingresado ese dato en la columna no se puede aplicar, se debe ingresar un valor en ese campo para actualizar.

Creo que lo correcto seria cargar via XML ese dato a la compania creada, alguna idea de como hacerlo ?
