### ISSUE TITLE
Fallo al instalar en ODOO V8 l1on_ec_pos

### ISSUE THREAD

**Issue by cholitoecuatoriano** [odoo-ecuador/odoo-ecuador#80]
La consola muestra el siguiente error: openerp.point_of_sale.load_db is not a function

Posible solución:
/l10n_ec_pos/static/src/js/pos.js
linea 290:  })()  a  });

No obstante en el pos no recupera los datos del campo ced_ruc

**Comment by ovnicraft** [comment]
@cholitoecuatoriano nos puedes indicar si tienes instalado el l10n_ec_partner ? 
En la noche realizo las pruebas del caso.

**Comment by cholitoecuatoriano** [comment]
Si los dos:
10n_ec_partner,
10n_ec_pos

**Comment by ovnicraft** [comment]
@cholitoecuatoriano no he podido reproducir el error, puedes enviarnos el trace completo.

**Comment by ovnicraft** [comment]
No hemos tenido actualizacion del error.
Lo cierro hasta nuevo aviso.

**Comment by ovnicraft** [comment]
confirmado

`raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: point_of_sale.assets_backend" while parsing None:4, near
<data name="posec assets" inherit_id="point_of_sale.assets_backend">
      <xpath expr="." position="inside">
    <script type="text/javascript" src="/l10n_ec_pos/static/src/js/pos.js"/>
      </xpath>
    </data>
`

**Comment by ovnicraft** [comment]
PR en #101

**Comment by ovnicraft** [comment]
Corregido.
