### ISSUE TITLE
Soporte

### ISSUE THREAD

**Issue by marceloandrader** [odoo-ecuador/odoo-ecuador#82]
Hola, veo que el proyecto es  muy activo, en cuántas empresas se ha instalado, si desearía instalar en una empresa, pueden dar soporte? (no gratis obviamente)

Gracias por su respuesta.

**Comment by ocurieles** [comment]
Buenas tardes claro que si, hemos instalado en varias empresas y 
seguimos en crecimiento, podemos apoyarle en la implementación, dejeme 
saber cuando podemos reunirnos para conocer sus necesidades.

  Quedo atento.

  Saludos.

**Comment by marceloandrader** [comment]
Gracias, dejeme conversar con las personas interesadas y le aviso.

**Comment by ovnicraft** [comment]
@ocurieles por favor cualquier servicio de soporte, utilizar los canales adecuados.
