### ISSUE TITLE
Comprobantes electronicos

### ISSUE THREAD

**Issue by ovnicraft** [odoo-ecuador/odoo-ecuador#9]
El SRI tiene un detalle de especificaciones para comprobantes electronicos, revisar el alcance.
El documento de especificaciones: https://mega.co.nz/#!wFt3BJpZ!R_BmWgDcWWPDjb3Bh8gEuDIzPptULjq0w1RF8em80do

**Comment by alcidesrivera** [comment]
Eso quiere decir que ya se encuentra implementado?

**Comment by ovnicraft** [comment]
No, el objetivo es incluirlo para el roadmap de la versión 7.0.

**Comment by ovnicraft** [comment]
Actualizacion con implementacion de factura y retencion.
Pendiente otros documentos electronicos, se abrira un issue para cada uno.
