### ISSUE TITLE
account_coda dependencia no encontrada

### ISSUE THREAD

**Issue by jairuque** [odoo-ecuador/odoo-ecuador#92]
Intenta instalar el módulo 'l10n_ec_chart' que depende del módulo 'account_coda'.
Este último módulo no está disponible en su sistema.

**Comment by ovnicraft** [comment]
@jairuque se actualizo el modulo https://github.com/odoo-ecuador/odoo-ecuador/blob/8.0/l10n_ec_chart/__openerp__.py#L14 y se elimino la dependencia.
