### ISSUE TITLE
l10n_ec_chart error to instal odoo v8

### ISSUE THREAD

**Issue by jairuque** [odoo-ecuador/odoo-ecuador#93]
XMLSyntaxError: Document is empty, line 1, column 1

**Comment by ovnicraft** [comment]
Nos ayudas con todo el traceback de la instalacion para identificar el error.

**Comment by ovnicraft** [comment]
@jairuque nos das un update del issue ?

**Comment by ovnicraft** [comment]
No tenemos update del modulo y el build no da error en su instalacion.
