### ISSUE TITLE
errores instalando "Advances Payment for Customers/Suppliers" (l10n_ec_advances)

### ISSUE THREAD

**Issue by Jaime2ndQuadrant** [odoo-ecuador/odoo-ecuador#98]
tuve problemas instalando este módulo, tal vez sea que no se usa mucho y no esta actualizado?
voy a desinstalarlo mientras me confirman, pero de todos modos adjunto el parche que me sirvió para poder instalar el módulo
[odoo8_ec_advances.patch.gz](https://github.com/odoo-ecuador/odoo-ecuador/files/292497/odoo8_ec_advances.patch.gz)

**Comment by ovnicraft** [comment]
@Jaime2ndQuadrant este modulo esta en reconstruccion, debemos agregar una tabla resumen de modulos usables.

Reviso tu patch.
